// SPDX-FileCopyrightText: sumu Authors
// SPDX-License-Identifier: AGPL-3.0

#include "icons.h"

#ifndef NOMINMAX
#define NOMINMAX // windows.h (via d3d11.h) would otherwise macro-break std::min/max below
#endif
#include <d3d11.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <unordered_map>
#include <vector>

#include <wrl/client.h>

#include "icons_atlas.h" // generated by native/cmake/embed_binary.cmake from assets/generated/icons_atlas.rgba

using Microsoft::WRL::ComPtr;

namespace ui::icons {
namespace {

struct GlyphStrip {
    ComPtr<ID3D11Texture2D> tex;
    ComPtr<ID3D11ShaderResourceView> srv;
};

ID3D11Device* s_device = nullptr;
std::unordered_map<int, GlyphStrip> s_cache; // keyed by glyph edge in physical px

// Area-weighted (box-integral) separable resample: every destination pixel integrates the
// exact source rectangle it covers, so minification is a true average (equivalent to
// (s/d)^2 supersampling) and never aliases. The glyphs are uniform white with straight
// alpha, so channel-independent filtering cannot produce color halos.
void resample_area(const uint8_t* src, int sw, int sh, uint8_t* dst, int dw, int dh, int dpitch){
    const float sx = static_cast<float>(sw) / dw, sy = static_cast<float>(sh) / dh;
    std::vector<float> tmp(static_cast<size_t>(dw) * sh * 4);
    for (int y = 0; y < sh; ++y) { // horizontal pass: sw -> dw per row
        const uint8_t* srow = src + static_cast<size_t>(y) * sw * 4;
        float* trow = tmp.data() + static_cast<size_t>(y) * dw * 4;
        for (int dx = 0; dx < dw; ++dx) {
            const float x0 = dx * sx, x1 = x0 + sx;
            float acc[4] = {0, 0, 0, 0};
            const int i_end = std::min(sw, static_cast<int>(std::ceil(x1)));
            for (int ix = static_cast<int>(x0); ix < i_end; ++ix) {
                const float w = std::min(x1, static_cast<float>(ix + 1)) - std::max(x0, static_cast<float>(ix));
                for (int c = 0; c < 4; ++c) acc[c] += w * srow[ix * 4 + c];
            }
            for (int c = 0; c < 4; ++c) trow[dx * 4 + c] = acc[c] / sx;
        }
    }
    for (int dy = 0; dy < dh; ++dy) { // vertical pass: sh -> dh per column
        const float y0 = dy * sy, y1 = y0 + sy;
        const int i_end = std::min(sh, static_cast<int>(std::ceil(y1)));
        for (int dx = 0; dx < dw; ++dx) {
            float acc[4] = {0, 0, 0, 0};
            for (int iy = static_cast<int>(y0); iy < i_end; ++iy) {
                const float w = std::min(y1, static_cast<float>(iy + 1)) - std::max(y0, static_cast<float>(iy));
                const float* t = tmp.data() + (static_cast<size_t>(iy) * dw + dx) * 4;
                for (int c = 0; c < 4; ++c) acc[c] += w * t[c];
            }
            uint8_t* o = dst + (static_cast<size_t>(dy) * dpitch + dx) * 4;
            for (int c = 0; c < 4; ++c)
                o[c] = static_cast<uint8_t>(std::clamp(acc[c] / sy + 0.5f, 0.0f, 255.0f));
        }
    }
}

// Builds (or fetches) a strip texture with all kIconCount glyphs resampled to g x g px.
ID3D11ShaderResourceView* glyph_srv(int g){
    auto it = s_cache.find(g);
    if (it != s_cache.end()) return it->second.srv.Get();
    if (!s_device) return nullptr;
    static_assert(kIconsAtlasW == kIconSrcPx * kIconCount && kIconsAtlasH == kIconSrcPx,
        "embedded strip layout must be kIconCount tightly packed kIconSrcPx cells");

    const int strip_w = g * kIconCount;
    std::vector<uint8_t> strip(static_cast<size_t>(strip_w) * g * 4);
    std::vector<uint8_t> cell(static_cast<size_t>(kIconSrcPx) * kIconSrcPx * 4);
    for (int i = 0; i < kIconCount; ++i) {
        for (int y = 0; y < kIconSrcPx; ++y) // cut the icon's cell out of the source strip
            std::memcpy(cell.data() + static_cast<size_t>(y) * kIconSrcPx * 4,
                kIconsAtlasRgba + (static_cast<size_t>(y) * kIconsAtlasW + i * kIconSrcPx) * 4,
                kIconSrcPx * 4);
        resample_area(cell.data(), kIconSrcPx, kIconSrcPx,
            strip.data() + static_cast<size_t>(i) * g * 4, g, g, strip_w);
    }

    GlyphStrip gs;
    D3D11_TEXTURE2D_DESC td{};
    td.Width = static_cast<UINT>(strip_w);
    td.Height = static_cast<UINT>(g);
    td.MipLevels = 1;
    td.ArraySize = 1;
    td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    td.SampleDesc.Count = 1;
    td.Usage = D3D11_USAGE_DEFAULT;
    td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    HRESULT hr = s_device->CreateTexture2D(&td, nullptr, &gs.tex);
    if (SUCCEEDED(hr)) {
        ComPtr<ID3D11DeviceContext> ctx;
        s_device->GetImmediateContext(&ctx);
        ctx->UpdateSubresource(gs.tex.Get(), 0, nullptr, strip.data(),
            static_cast<UINT>(strip_w * 4), 0);
        hr = s_device->CreateShaderResourceView(gs.tex.Get(), nullptr, &gs.srv);
    }
    if (FAILED(hr)) {
        fprintf(stderr, "[sumu] icon glyph strip %dpx create failed hr=0x%08lx -- icons disabled for this size\n",
            g, static_cast<unsigned long>(hr));
        return nullptr;
    }
    return s_cache.emplace(g, std::move(gs)).first->second.srv.Get();
}

} // namespace

void init(ID3D11Device* device){
    shutdown();
    s_device = device;
}

void shutdown(){
    s_cache.clear();
    s_device = nullptr;
}

bool available(){
    return s_device != nullptr;
}

void draw(ImDrawList* dl, const ImVec2& p_min, const ImVec2& p_max, AppIcon icon, ImU32 col){
    if (!dl) return;
    // Snap to whole physical pixels: at fractional DPI scales (e.g. 150%) the centered
    // rects land on .5 coordinates, and sampling between pixels softens the strokes.
    const ImVec2 a(std::floor(p_min.x), std::floor(p_min.y));
    const int g = std::max(2, static_cast<int>(std::floor(p_max.y) - a.y));
    ID3D11ShaderResourceView* srv = glyph_srv(g);
    if (!srv) return;
    const float u0 = static_cast<float>(static_cast<int>(icon)) / kIconCount;
    dl->AddImage((ImTextureID)(intptr_t)srv,
        a, ImVec2(a.x + static_cast<float>(g), a.y + static_cast<float>(g)),
        ImVec2(u0, 0.0f), ImVec2(u0 + 1.0f / kIconCount, 1.0f), col);
}

} // namespace ui::icons
