# SPDX-FileCopyrightText: sumu Authors
# SPDX-License-Identifier: AGPL-3.0
#
# Embed a binary file into a generated C++ header as a uint8_t array.
# Usage:
#   cmake -DIN=<path> -DOUT=<path> -DVARNAME=<name> -DWIDTH=<w> -DHEIGHT=<h> -P embed_binary.cmake
#
# Produces:
#   static constexpr int kLogoW / kLogoH / kLogoRgbaBytes
#   static const uint8_t kLogoRgba[N] = { ... };
# (names derived from VARNAME: k${VARNAME}W etc. for VARNAME=Logo)

if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED VARNAME)
    message(FATAL_ERROR "embed_binary.cmake requires -DIN=, -DOUT=, -DVARNAME=")
endif()
if(NOT DEFINED WIDTH OR NOT DEFINED HEIGHT)
    message(FATAL_ERROR "embed_binary.cmake requires -DWIDTH=, -DHEIGHT=")
endif()

file(READ "${IN}" _raw HEX)
string(LENGTH "${_raw}" _hex_len)
math(EXPR _nbytes "${_hex_len} / 2")
math(EXPR _expected "${WIDTH} * ${HEIGHT} * 4")
if(NOT _nbytes EQUAL _expected)
    message(FATAL_ERROR "embed_binary: ${IN} is ${_nbytes} bytes, expected ${_expected} (${WIDTH}x${HEIGHT} RGBA)")
endif()

# Format as "0xab,0xcd,..." via ONE regex pass over the hex string. The old per-byte
# SUBSTRING+append loop was O(n^2) in CMake string time -- fine for the 256KB logo, but it
# hung the build for tens of minutes on the ~900KB icon atlas.
string(REGEX REPLACE "(..)" "0x\\1," _body "${_raw}")
# Wrap to 16 bytes per line so the compiler doesn't see one giant line.
string(REGEX REPLACE "((0x..,){16})" "\\1\n    " _body "${_body}")

set(_header
"// SPDX-FileCopyrightText: sumu Authors
// SPDX-License-Identifier: AGPL-3.0
//
// AUTO-GENERATED by native/cmake/embed_binary.cmake from ${IN} -- do not edit.
#pragma once

#include <cstdint>

static constexpr int k${VARNAME}W = ${WIDTH};
static constexpr int k${VARNAME}H = ${HEIGHT};
static constexpr int k${VARNAME}RgbaBytes = ${_nbytes};

static const uint8_t k${VARNAME}Rgba[k${VARNAME}RgbaBytes] = {
${_body}};
")

file(WRITE "${OUT}" "${_header}")
