# SPDX-FileCopyrightText: sumu Authors
# SPDX-License-Identifier: AGPL-3.0
#
# Embed a binary file into a generated C++ header as a uint8_t array.
# Usage:
#   cmake -DIN=<path> -DOUT=<path> -DVARNAME=<name> -DWIDTH=<w> -DHEIGHT=<h> -P embed_binary.cmake
#
# Produces:
#   static constexpr int kLogoW / kLogoH / kLogoRgbaBytes
#   static const uint8_t kLogoRgba[N] = { ... };
# (names derived from VARNAME: k${VARNAME}W etc. for VARNAME=Logo)

if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED VARNAME)
    message(FATAL_ERROR "embed_binary.cmake requires -DIN=, -DOUT=, -DVARNAME=")
endif()
if(NOT DEFINED WIDTH OR NOT DEFINED HEIGHT)
    message(FATAL_ERROR "embed_binary.cmake requires -DWIDTH=, -DHEIGHT=")
endif()

file(READ "${IN}" _raw HEX)
string(LENGTH "${_raw}" _hex_len)
math(EXPR _nbytes "${_hex_len} / 2")
math(EXPR _expected "${WIDTH} * ${HEIGHT} * 4")
if(NOT _nbytes EQUAL _expected)
    message(FATAL_ERROR "embed_binary: ${IN} is ${_nbytes} bytes, expected ${_expected} (${WIDTH}x${HEIGHT} RGBA)")
endif()

# Format as "0xab, 0xcd, ..." with 16 bytes per line.
set(_body "")
set(_line "")
set(_count 0)
set(_i 0)
while(_i LESS _hex_len)
    string(SUBSTRING "${_raw}" ${_i} 2 _byte)
    if(_line STREQUAL "")
        set(_line "0x${_byte}")
    else()
        set(_line "${_line}, 0x${_byte}")
    endif()
    math(EXPR _count "${_count} + 1")
    math(EXPR _i "${_i} + 2")
    if(_count EQUAL 16)
        if(_i LESS _hex_len)
            set(_body "${_body}    ${_line},\n")
        else()
            set(_body "${_body}    ${_line}\n")
        endif()
        set(_line "")
        set(_count 0)
    endif()
endwhile()
if(NOT _line STREQUAL "")
    set(_body "${_body}    ${_line}\n")
endif()

set(_header
"// SPDX-FileCopyrightText: sumu Authors
// SPDX-License-Identifier: AGPL-3.0
//
// AUTO-GENERATED by native/cmake/embed_binary.cmake from ${IN} -- do not edit.
#pragma once

#include <cstdint>

static constexpr int k${VARNAME}W = ${WIDTH};
static constexpr int k${VARNAME}H = ${HEIGHT};
static constexpr int k${VARNAME}RgbaBytes = ${_nbytes};

static const uint8_t k${VARNAME}Rgba[k${VARNAME}RgbaBytes] = {
${_body}};
")

file(WRITE "${OUT}" "${_header}")
