// SPDX-FileCopyrightText: sumu Authors
// SPDX-License-Identifier: AGPL-3.0
//
// sumu's promoted native present kernel (pybind11 module `sumu_core`, class `Player`).
// Promoted from the three validated spikes (see docs/spike_results.md):
//   - spike0_d3d11_present: D3D11 flip-model swapchain + FFmpeg d3d11va zero-copy decode.
//   - spike1_cuda_interop:  CUDA driver-API + torch primary context, zero-copy CUDA<->D3D11.
//   - spike2_clock_mixing:  three-thread clock-driven mixing kernel (decode thread + original
//                           ring buffer, AI-push thread + ready-map, present thread wall-clock
//                           frame picking, single explicit d3d_mutex_ serializing ALL threads'
//                           touches of the shared D3D11/CUDA-interop context -- this was
//                           spike2's key architectural finding and is preserved verbatim).
//
// New in this promotion: seek(frame_num) as a REPOSITION, not a teardown (I6) -- see the
// seek() method below and docs/native_core.md for the full design writeup and measurements.
//
// Threading model (unchanged from spike2, see spike2's presenter.cpp header for the full
// story of why a single d3d_mutex_ is required on top of ID3D11Multithread::SetMultithread-
// Protected(TRUE)):
//   - decode thread:  FFmpeg d3d11va decode -> CopySubresourceRegion into a persistent NV12
//                     "passthrough ring" Texture2DArray, throttled to stay within
//                     kDecodeAheadMax frames of the present head.
//   - AI-push thread (Python, not owned here): push_ai_frame() does the CUDA<->D3D11
//                     zero-copy bridge into a landing texture, then a CopySubresourceRegion
//                     into the AI ready-map's Texture2DArray slot, THEN marks that slot ready.
//   - present thread: wall-clock QPC pacing, picks AI-fresh -> passthrough-fresh -> repeat-
//                     last-shown every tick, NEVER blocks on decode or AI-push.
//
// seek()'s concurrency contract (the new part): `decoder_mutex_` now wraps not just the
// Decoder object itself but the WHOLE "produce one frame, copy it into the ring, tag it
// ready" sequence in BOTH decode_loop() and seek() -- widened from spike2's narrower "just
// guard the Decoder object" scope. This makes "decode one frame and publish it" an atomic
// unit with respect to seek(), which is what closes a real race: without this widening, a
// frame the decode thread had already pulled from the OLD position (in flight between
// Decoder::next_frame() returning and its ring-write+tag landing) could still land in the
// ring AFTER seek()'s own fresh write to the same slot, silently overwriting the just-sought
// frame with stale content while its tag looked fine. See docs/native_core.md for the full
// writeup and the seek-stress measurements that exercised this path.

#ifndef NOMINMAX
#define NOMINMAX // windows.h's min/max macros otherwise break std::min/std::max call sites below
#endif
#include <windows.h>
#include <d3d11.h>
#include <d3d11_4.h>
#include <dxgi1_2.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <timeapi.h>
#pragma comment(lib, "winmm.lib")

#include <cuda.h>
#include <cudaD3D11.h>

#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx11.h"

// imgui_impl_win32.h wraps this declaration in `#if 0` (to avoid dragging a <windows.h>
// dependency into that header) and its own comment directs callers to copy the line into
// their .cpp -- windows.h is already included above, so this is safe here.
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <atomic>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

#include "decoder.h"
#include "present_hlsl.h" // generated by native/cmake/embed_shader.cmake from native/shaders/present.hlsl

namespace py = pybind11;
using Microsoft::WRL::ComPtr;

namespace {

// ---- error helpers -----------------------------------------------------------------------

void check_hr(HRESULT hr, const char* what)
{
    if (FAILED(hr)) {
        char buf[256];
        snprintf(buf, sizeof(buf), "%s failed: hr=0x%08lx", what, hr);
        throw std::runtime_error(buf);
    }
}

void check_cu(CUresult res, const char* what)
{
    if (res != CUDA_SUCCESS) {
        const char* name = nullptr;
        const char* desc = nullptr;
        cuGetErrorName(res, &name);
        cuGetErrorString(res, &desc);
        char buf[512];
        snprintf(buf, sizeof(buf), "%s failed: CUresult=%d (%s: %s)", what,
            static_cast<int>(res), name ? name : "?", desc ? desc : "?");
        throw std::runtime_error(buf);
    }
}

// ---- global Win32 state (one window per process, fine for this player) --------------------
bool g_quit = false;

// M3: WndProc's DEFINITION now lives in a reopened instance of this same anonymous namespace,
// placed after class Player's closing brace -- it needs a COMPLETE Player type to route input
// to a specific instance (GWLP_USERDATA -> Player*, see create_window()) and to call its
// record_toggle_play()/record_seek()/ui_ready() methods. This forward declaration is all
// create_window()'s WNDCLASSEXA::lpfnWndProc assignment needs. Unnamed namespaces reopened
// later in the same translation unit are the SAME namespace, so g_quit above stays visible
// there unqualified, and this declaration and that definition refer to the same entity.
LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp);

double pctile(std::vector<double>& sorted_ms, double q)
{
    if (sorted_ms.empty()) return 0.0;
    double pos = q * (sorted_ms.size() - 1);
    size_t lo = static_cast<size_t>(pos);
    size_t hi = std::min(lo + 1, sorted_ms.size() - 1);
    double frac = pos - lo;
    return sorted_ms[lo] * (1.0 - frac) + sorted_ms[hi] * frac;
}

py::dict summarize(std::vector<double> samples_ms)
{
    py::dict d;
    if (samples_ms.empty()) {
        d["n"] = 0; d["median_ms"] = 0.0; d["p99_ms"] = 0.0; d["max_ms"] = 0.0; d["mean_ms"] = 0.0;
        return d;
    }
    std::sort(samples_ms.begin(), samples_ms.end());
    double sum = 0.0;
    for (double v : samples_ms) sum += v;
    d["n"] = samples_ms.size();
    d["median_ms"] = pctile(samples_ms, 0.5);
    d["p99_ms"] = pctile(samples_ms, 0.99);
    d["max_ms"] = samples_ms.back();
    d["min_ms"] = samples_ms.front();
    d["mean_ms"] = sum / samples_ms.size();
    return d;
}

// Present-tick "source" tags recorded in the trace, distinguishing a freshly-drawn frame
// from a repeat-of-last-frame fallback (the latter should be ~never once steady, except
// briefly right after a seek while decode catches up to the new position).
enum class Source : int8_t {
    PassthroughFresh = 0,
    AiFresh = 1,
    PassthroughStale = 2, // re-presented because neither map had this exact frame_num
    AiStale = 3,
};

bool is_ai(Source s) { return s == Source::AiFresh || s == Source::AiStale; }

// ---- seekbar x<->frame mapping (M3) -------------------------------------------------------
// Pure, no ImGui/Player/D3D dependency -- unit-testable in isolation. Placed here (in the
// anonymous namespace, above class Player) is sufficient for Player's own member functions to
// call them: C++ defers compiling member-function BODIES until after the class's closing
// brace has been seen ("complete-class context"), so any free function visible earlier in the
// translation unit -- including here -- is visible to every Player method body, regardless of
// where in the class the method itself is declared.
//
// Boundary behavior: frame_count<=0 (not-yet-opened/empty video) always maps to/from frame 0.
// x is clamped to [x0,x1] before mapping, so a drag past either edge clamps to frame 0 /
// frame_count-1, never out of bounds. float->frame uses round (llround), not truncation, so a
// pixel exactly between two frame boundaries maps to the CLOSER frame rather than always the
// earlier one.
int64_t frame_for_seekbar_x(float mx, float x0, float x1, int64_t frame_count)
{
    if (frame_count <= 0) return 0;
    if (x1 <= x0) return 0;
    float t = (mx - x0) / (x1 - x0);
    t = std::clamp(t, 0.0f, 1.0f);
    int64_t last = frame_count - 1;
    int64_t f = static_cast<int64_t>(std::llround(static_cast<double>(t) * static_cast<double>(last)));
    return std::clamp<int64_t>(f, 0, last);
}

float seekbar_x_for_frame(int64_t frame, float x0, float x1, int64_t frame_count)
{
    if (frame_count <= 1) return x0; // avoids a div-by-zero on `last` below when there's <=1 frame
    int64_t last = frame_count - 1;
    frame = std::clamp<int64_t>(frame, 0, last);
    float t = static_cast<float>(frame) / static_cast<float>(last);
    return x0 + t * (x1 - x0);
}

std::string basename_of(const std::string& path)
{
    size_t pos = path.find_last_of("/\\");
    return (pos == std::string::npos) ? path : path.substr(pos + 1);
}

std::string format_mmss(double seconds)
{
    if (seconds < 0.0) seconds = 0.0;
    int64_t total = static_cast<int64_t>(seconds + 0.5);
    int64_t m = total / 60;
    int64_t s = total % 60;
    char buf[32];
    snprintf(buf, sizeof(buf), "%lld:%02lld", static_cast<long long>(m), static_cast<long long>(s));
    return std::string(buf);
}

// ---- AI input bridge shader (additive, Part B) --------------------------------------------
// Compiled inline via D3DCompile (NOT routed through native/cmake/embed_shader.cmake's
// present.hlsl pipeline -- that file is promoted/validated code and stays untouched). Ported
// verbatim from spikes/spike3_nv12_interop/src/interop.cpp's validated kShaderSrc: a
// point-sampled fullscreen triangle that does an exact 1:1 texel identity copy (no filtering,
// no colour conversion -- this is purely a format-reinterpretation blit, see the plane-SRV-
// override technique documented in docs/spike3_nv12_interop.md).
const char* kAiInputBlitShaderSrc = R"HLSL(
Texture2D    tex   : register(t0);
SamplerState samp0 : register(s0);

struct VSOut
{
    float4 pos : SV_Position;
    float2 uv  : TEXCOORD0;
};

VSOut VSMain(uint vid : SV_VertexID)
{
    float2 pos[3] = { float2(-1.0, -1.0), float2(-1.0, 3.0), float2(3.0, -1.0) };
    float2 uv[3]  = { float2(0.0, 1.0),   float2(0.0, -1.0), float2(2.0, 1.0) };
    VSOut o;
    o.pos = float4(pos[vid], 0.0, 1.0);
    o.uv = uv[vid];
    return o;
}

float PSMain_Y(VSOut i) : SV_Target
{
    return tex.Sample(samp0, i.uv).r;
}

float2 PSMain_UV(VSOut i) : SV_Target
{
    return tex.Sample(samp0, i.uv).rg;
}
)HLSL";

} // namespace

// ---- UI draw-data snapshot (M2: main-thread NewFrame/Render -> present-thread RenderDrawData
// handoff) --------------------------------------------------------------------------------
//
// ImGui::GetDrawData()'s ImDrawList*s are owned by the ImGuiContext and get overwritten by the
// next NewFrame() -- unsafe to hand across threads by pointer. CloneOutput() (imgui_draw.cpp)
// deep-copies each ImDrawList's CmdBuffer/IdxBuffer/VtxBuffer into a freshly IM_NEW'd
// ImDrawList, so a snapshot built from CloneOutput() is safe for the present thread to read
// after the main thread has moved on to its next frame. IM_NEW/IM_DELETE route through
// ImGui::MemAlloc/MemFree (imgui.h's IM_NEW/IM_DELETE macros), so cloned lists must be freed
// with IM_DELETE, not plain `delete` -- matches ImGuiViewportP::~ImGuiViewportP's own use of
// IM_DELETE on BgFgDrawLists (imgui.h:1988), the only other place in this vendored tree that
// owns/frees a raw ImDrawList*.
struct UiDrawSnapshot {
    ImVector<ImDrawList*> cmd_lists; // each entry is a CloneOutput() result -- owned here
    int total_vtx = 0;
    int total_idx = 0;
    ImVec2 display_pos{};
    ImVec2 display_size{};
    ImVec2 framebuffer_scale{};

    ~UiDrawSnapshot()
    {
        for (ImDrawList* dl : cmd_lists) IM_DELETE(dl);
    }
};

// ---- UI intent channel (M3) -----------------------------------------------------------
// Main-thread-exclusive state recording what the UI wants to happen next, drained once per
// Python main-loop tick by Player::take_ui_intents(). Deliberately NOT mutex-guarded: WndProc
// (reached via pump_messages()) and ui_tick()/build_*() all run on the SAME Python-owned main
// thread, and so does take_ui_intents() -- the present thread never reads this struct. Adding
// a lock here would be the wrong signal (that this got used across threads), see DESIGN.md I2
// (present never touches transport/config).
struct UiIntents {
    std::optional<int64_t> seek;
    bool toggle_play = false;
    std::optional<int> clip_length;
    std::optional<int> max_regions;
};

// ---------------------------------------------------------------------------------------
class Player
{
public:
    // Ring capacity in frames (~1s at 60fps): both the passthrough decode-ahead buffer and
    // the AI ready-map share this capacity/indexing scheme (see docs/spike_results.md's
    // spike2 writeup for the E_OUTOFMEMORY history behind this number).
    static constexpr UINT kRingCapacity = 64;
    static constexpr int64_t kDecodeAheadMax = static_cast<int64_t>(kRingCapacity) - 10;
    static constexpr int64_t kStartBufferFrames = 5;

    Player(int width_hint, int height_hint, bool maximized)
    {
        timeBeginPeriod(1);
        timer_period_set_ = true;

        create_window(width_hint, height_hint, maximized);
        create_device_and_swapchain();
        create_shader_pipeline();
        ui_init(); // present thread not started yet (starts in open()) -- no context
                   // contention for this one-time ImGui/backend warmup.
        init_cuda_driver(); // device-independent-of-video-size CUDA setup only; landing
                             // texture + registration happen in open() once src dims are known.
    }

    ~Player() { close(); }

    // ---- lifecycle -------------------------------------------------------------------------

    void open(const std::string& video_path)
    {
        if (opened_) throw std::runtime_error("Player.open() called twice on the same Player");

        video_path_ = video_path; // UI displays basename_of(video_path_) in the top bar

        std::string decode_err;
        if (!decoder_.open(video_path, device_.Get(), decode_err))
            throw std::runtime_error("decoder.open failed: " + decode_err);
        fps_ = decoder_.fps();
        src_width_ = decoder_.width();
        src_height_ = decoder_.height();
        frame_count_ = decoder_.frame_count();
        if (src_width_ <= 0 || src_height_ <= 0)
            throw std::runtime_error("decoder reported invalid dimensions");

        create_ring_resources();
        create_landing_texture();
        register_landing_with_cuda();
        create_ai_input_bridge();

        pt_tag_.assign(kRingCapacity, -1);
        ai_tag_.assign(kRingCapacity, -1);

        QueryPerformanceFrequency(&freq_);

        // Decode thread starts immediately and races ahead (throttled) of the present head,
        // which is still -1 (not started) at this point -- the throttle treats a not-yet-
        // started present head as "0" so decode can still build the initial buffer.
        stop_.store(false, std::memory_order_relaxed);
        decode_thread_ = std::thread(&Player::decode_loop, this);

        LARGE_INTEGER t0;
        QueryPerformanceCounter(&t0);
        for (;;) {
            if (pt_high_water_.load(std::memory_order_relaxed) >= kStartBufferFrames - 1)
                break;
            LARGE_INTEGER now;
            QueryPerformanceCounter(&now);
            double waited_s = static_cast<double>(now.QuadPart - t0.QuadPart) / qpc_freq_d();
            if (waited_s > 10.0)
                throw std::runtime_error("decode thread failed to buffer initial frames within 10s");
            Sleep(1);
        }

        // Start paused at frame 0 -- caller must call play() to start the wall clock.
        anchor_frame_.store(0, std::memory_order_relaxed);
        clock_frame_.store(0, std::memory_order_relaxed);
        present_head_frame_.store(0, std::memory_order_relaxed);
        playing_.store(false, std::memory_order_relaxed);
        QueryPerformanceCounter(&pace_origin_qpc_);
        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        anchor_qpc_ticks_.store(now.QuadPart, std::memory_order_relaxed);

        opened_ = true;
        present_thread_ = std::thread(&Player::present_loop, this);
    }

    void close()
    {
        if (closed_) return;
        closed_ = true;
        stop_.store(true, std::memory_order_relaxed);
        if (decode_thread_.joinable()) decode_thread_.join();
        if (present_thread_.joinable()) present_thread_.join();

        // Present thread (the only ImGui-touching thread in M1) has now joined -- safe to
        // tear down ImGui's device objects/context before DestroyWindow below.
        ui_shutdown();

        if (cu_res_) { cuGraphicsUnregisterResource(cu_res_); cu_res_ = nullptr; }
        // AI input bridge teardown (additive, Part B) -- mirrors cu_res_'s cleanup above,
        // must also happen before the primary context itself is released.
        if (ai_in_cu_res_y_) { cuGraphicsUnregisterResource(ai_in_cu_res_y_); ai_in_cu_res_y_ = nullptr; }
        if (ai_in_cu_res_uv_) { cuGraphicsUnregisterResource(ai_in_cu_res_uv_); ai_in_cu_res_uv_ = nullptr; }
        if (ai_in_cu_buf_) { cuMemFree(ai_in_cu_buf_); ai_in_cu_buf_ = 0; }
        if (cu_ctx_) { cuCtxSetCurrent(nullptr); cuDevicePrimaryCtxRelease(cu_dev_); cu_ctx_ = nullptr; }

        decoder_.close();

        if (hwnd_) { DestroyWindow(hwnd_); hwnd_ = nullptr; }
        if (timer_period_set_) { timeEndPeriod(1); timer_period_set_ = false; }
    }

    void pump_messages()
    {
        MSG msg{};
        while (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE)) {
            if (msg.message == WM_QUIT) { g_quit = true; break; }
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }

    bool should_quit() const { return g_quit; }

    // ---- transport control -------------------------------------------------------------

    void play()
    {
        require_open();
        if (playing_.load(std::memory_order_relaxed)) return;
        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        anchor_qpc_ticks_.store(now.QuadPart, std::memory_order_relaxed);
        anchor_frame_.store(clock_frame_.load(std::memory_order_relaxed), std::memory_order_relaxed);
        playing_.store(true, std::memory_order_relaxed);
    }

    void pause()
    {
        require_open();
        if (!playing_.load(std::memory_order_relaxed)) return;
        anchor_frame_.store(clock_frame_.load(std::memory_order_relaxed), std::memory_order_relaxed);
        playing_.store(false, std::memory_order_relaxed);
    }

    bool is_playing() const { return playing_.load(std::memory_order_relaxed); }

    // ---- UI (M2): main thread only -- NewFrame/build/Render/CloneOutput, publish snapshot ---
    //
    // Called once per Python-driven tick (pybind's ui_tick()). Never touches d3d_mutex_ (see
    // the context-touch audit above ui_init(), private section below -- nothing here issues
    // D3D11 calls except the CPU-side font-atlas bookkeeping inside ImGui::NewFrame(), which is
    // backend-agnostic). Defined here in the public section (pybind must bind it directly);
    // ui_init()/ui_shutdown()/ui_render_drawdata() stay private since only this class's own
    // methods call them.
    void ui_tick()
    {
        if (!ui_ready_) return;

        ImGui_ImplDX11_NewFrame();
        ImGui_ImplWin32_NewFrame();
        ImGui::NewFrame();
        build_ui(); // M3: real product UI (top bar / bottom bar / settings panel).
        ImGui::Render();

        ImDrawData* dd = ImGui::GetDrawData();
        auto snap = std::make_unique<UiDrawSnapshot>();
        snap->total_vtx = dd->TotalVtxCount;
        snap->total_idx = dd->TotalIdxCount;
        snap->display_pos = dd->DisplayPos;
        snap->display_size = dd->DisplaySize;
        snap->framebuffer_scale = dd->FramebufferScale;
        snap->cmd_lists.resize(dd->CmdLists.Size);
        for (int i = 0; i < dd->CmdLists.Size; ++i)
            snap->cmd_lists[i] = dd->CmdLists[i]->CloneOutput();

        std::lock_guard<std::mutex> lk(ui_mutex_);
        ui_pending_ = std::move(snap); // O(1) pointer move, only moment ui_mutex_ is held here
    }

    // ---- UI intent recording (M3): main-thread-only. Called from WndProc (keyboard, via
    // pump_messages()) and from build_top_bar()/build_bottom_bar() (mouse, via ui_tick()) --
    // both run on the SAME Python-owned main thread. NEVER called from the present thread. No
    // lock: see UiIntents' own header comment. A second record_seek() before Python drains
    // simply overwrites the pending target (last-write-wins, which is what continuous seekbar
    // dragging wants).
    void record_toggle_play() { ui_intents_.toggle_play = true; }
    void record_seek(int64_t f) { ui_intents_.seek = f; }

    const std::string& path() const { return video_path_; }
    bool ui_ready() const { return ui_ready_; }

    // ---- UI config/intents channel (M3): main-thread-exclusive, Python-driven ---------------
    //
    // Python's main-thread loop calls these once per its own tick, bracketing ui_tick():
    // set_ui_config() (refresh the settings panel's read-only mirror of the ACTUAL committed
    // config -- Python owns the real SchedulerConfig, this is display-only) -> ui_tick()
    // (pump input via WndProc/pump_messages(), build UI, record intents) -> take_ui_intents()
    // (drain + execute). All three run on Python's single main thread, never the present
    // thread, so ui_intents_/ui_cfg_* need no lock.
    void set_ui_config(int clip_length, int max_regions)
    {
        ui_cfg_clip_length_ = clip_length;
        ui_cfg_max_regions_ = max_regions;
    }

    py::dict take_ui_intents()
    {
        py::dict d;
        d["seek"] = ui_intents_.seek.has_value() ? py::cast(*ui_intents_.seek) : py::none();
        d["toggle_play"] = ui_intents_.toggle_play;
        d["clip_length"] = ui_intents_.clip_length.has_value() ? py::cast(*ui_intents_.clip_length) : py::none();
        d["max_regions"] = ui_intents_.max_regions.has_value() ? py::cast(*ui_intents_.max_regions) : py::none();
        ui_intents_ = UiIntents{}; // drain
        return d;
    }

    // I6: seek = reposition, never teardown. Never touches decode_thread_/present_thread_/
    // decoder_/swapchain_ lifetime. Synchronous cost is dominated by Decoder::seek_to_frame's
    // own av_seek_frame + forward-decode-to-target (measured in docs/native_core.md); this
    // function does a bounded, small amount of extra D3D11/bookkeeping work on top of that
    // and returns -- it does NOT wait for steady playback to resume (that happens
    // organically on the decode/present threads, per I2/I9, never blocking).
    //
    // Returns the ACTUAL landed frame number (I5: anchored to the real decoded PTS, which
    // may differ slightly from the requested frame_num near GOP boundaries or EOF).
    int64_t seek(int64_t frame_num)
    {
        require_open();
        if (frame_count_ > 0) {
            frame_num = std::max<int64_t>(0, std::min<int64_t>(frame_num, frame_count_ - 1));
        } else {
            frame_num = std::max<int64_t>(0, frame_num);
        }

        // Widened lock: makes "seek the decoder, copy the landed frame into the ring, tag
        // it ready" one atomic unit with respect to decode_loop()'s own "decode one frame,
        // copy it, tag it" unit -- see the file header for the race this closes.
        std::lock_guard<std::mutex> decoder_lock(decoder_mutex_);

        DecodedFrame df;
        std::string err;
        if (!decoder_.seek_to_frame(frame_num, df, err))
            throw std::runtime_error("seek_to_frame failed: " + err);

        int64_t actual_frame = static_cast<int64_t>(std::llround(df.pts_seconds * fps_));
        UINT slot = wrap_slot(actual_frame);

        {
            std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
            context_->CopySubresourceRegion(pt_ring_tex_.Get(), slot, 0, 0, 0,
                df.texture, df.array_slice, nullptr);
        }
        {
            // Clear the WHOLE ready-map (both rings): a seek invalidates essentially all of
            // a ~1s-deep buffer relative to the new position anyway (I6's "reset" step), and
            // clearing unconditionally is simplest-and-safe (present's fallback path never
            // blocks even if a slot briefly shows stale content, so being conservative here
            // costs nothing but a few repeated-frame present ticks while decode refills).
            std::lock_guard<std::mutex> lk(ready_mutex_);
            std::fill(pt_tag_.begin(), pt_tag_.end(), -1);
            std::fill(ai_tag_.begin(), ai_tag_.end(), -1);
            pt_tag_[slot] = actual_frame;
        }

        pt_high_water_.store(actual_frame, std::memory_order_relaxed);
        present_head_frame_.store(actual_frame, std::memory_order_relaxed);

        // Reposition the present clock anchor. If playing, present continues from here at
        // full speed; if paused, the frozen frame moves to actual_frame.
        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        anchor_qpc_ticks_.store(now.QuadPart, std::memory_order_relaxed);
        anchor_frame_.store(actual_frame, std::memory_order_relaxed);
        clock_frame_.store(actual_frame, std::memory_order_relaxed);

        // Tell the freshly-seeked slot/source to present_loop's stale-repeat fallback too,
        // so a post-seek tick that (due to scheduling) lands past actual_frame before decode
        // catches up repeats the CORRECT just-sought frame, not whatever was on screen pre-
        // seek. Guarded by ready_mutex_ alongside the tag arrays it's read next to.
        {
            std::lock_guard<std::mutex> lk(ready_mutex_);
            seek_slot_hint_.store(static_cast<int64_t>(slot), std::memory_order_relaxed);
        }
        seek_version_.fetch_add(1, std::memory_order_relaxed);

        return actual_frame;
    }

    // ---- AI insertion point --------------------------------------------------------------

    // dev_ptr: CUdeviceptr (torch tensor's data_ptr()) for a contiguous uint8 RGBA8 (H,W,4)
    // tensor representing the AI-processed frame for content frame number `frame_num`. Never
    // blocks the present thread -- only ever touches the small landing texture via CUDA,
    // then a single D3D11 copy into the ready-map slot, then flips that slot's tag.
    void push_ai_frame(int64_t frame_num, uint64_t dev_ptr, int fwidth, int fheight, size_t pitch_bytes)
    {
        require_open();
        if (fwidth != src_width_ || fheight != src_height_)
            throw std::runtime_error("push_ai_frame: frame size does not match source video size");

        std::lock_guard<std::mutex> push_lock(push_mutex_); // defensive: single-producer assumed

        // push_ai_frame is called from whatever OS thread Python's AI-producer thread is --
        // driver-API calls issued directly here do not get CUDA runtime's lazy implicit
        // context attach, so make it explicit and unconditional.
        check_cu(cuCtxSetCurrent(cu_ctx_), "cuCtxSetCurrent (push_ai_frame)");

        std::lock_guard<std::mutex> d3d_lock(d3d_mutex_); // serializes ALL D3D11/CUDA-interop use of the shared context

        try {
            check_cu(cuGraphicsMapResources(1, &cu_res_, 0), "cuGraphicsMapResources");
            CUarray cu_arr = nullptr;
            check_cu(cuGraphicsSubResourceGetMappedArray(&cu_arr, cu_res_, 0, 0),
                "cuGraphicsSubResourceGetMappedArray");

            CUDA_MEMCPY2D cp{};
            cp.srcMemoryType = CU_MEMORYTYPE_DEVICE;
            cp.srcDevice = static_cast<CUdeviceptr>(dev_ptr);
            cp.srcPitch = pitch_bytes;
            cp.dstMemoryType = CU_MEMORYTYPE_ARRAY;
            cp.dstArray = cu_arr;
            cp.WidthInBytes = static_cast<size_t>(fwidth) * 4;
            cp.Height = static_cast<size_t>(fheight);
            check_cu(cuMemcpy2D(&cp), "cuMemcpy2D (device -> mapped landing array)");

            check_cu(cuGraphicsUnmapResources(1, &cu_res_, 0), "cuGraphicsUnmapResources");

            UINT slot = wrap_slot(frame_num);
            context_->CopySubresourceRegion(ai_ring_tex_.Get(), slot, 0, 0, 0,
                landing_tex_.Get(), 0, nullptr);

            {
                std::lock_guard<std::mutex> lk(ready_mutex_);
                ai_tag_[slot] = frame_num; // only mark ready AFTER the copy above is issued
            }
            ++ai_push_count_;
        } catch (const std::exception& e) {
            HRESULT removed = device_ ? device_->GetDeviceRemovedReason() : S_OK;
            char buf[768];
            snprintf(buf, sizeof(buf), "%s [device_removed_reason=0x%08lx]", e.what(),
                static_cast<unsigned long>(removed));
            throw std::runtime_error(buf);
        }
    }

    // ---- AI input bridge (additive, Part B) -----------------------------------------------
    //
    // Reverse direction of push_ai_frame(): decoder-produced D3D11 NV12 (already landed in
    // pt_ring_tex_ by decode_loop()/seek(), unmodified) -> CUDA, for Python's AI-consumer
    // thread to pull frames by number. Productionizes the technique validated in
    // spikes/spike3_nv12_interop (see docs/spike3_nv12_interop.md) and follows that spike's
    // own sumu_core API recommendation: keep this bridge and the colour-convert step separate
    // (colour-convert -- `_nv12_to_bgr_hwc_gpu`, python/sumu/ai/utils/video_utils.py -- is
    // NOT done here), and expose a frame-number-indexed, non-blocking API rather than a bare
    // "next decoded frame" (I5's ready-map contract).
    //
    // Genuine simplification vs. spike3: spike3 blitted directly off the DECODER's own
    // hw_frames_ctx texture, which FFmpeg's d3d11va hwaccel allocates at the macroblock-
    // padded CODED size (not the display size) -- that spike had to lazily probe the real
    // texture size via GetDesc() before sizing its plane targets, to avoid a silent vertical-
    // stretch bug (see spike3's "macroblock-padded decode texture" writeup). Player's own
    // pt_ring_tex_ has ALREADY been cropped to src_width_/src_height_ (display size) by
    // decode_loop()'s/seek()'s own CopySubresourceRegion calls (existing, unmodified code) --
    // so sourcing this bridge's identity blit from pt_ring_tex_'s existing per-slot SRVs
    // (pt_srv_y_/pt_srv_uv_, already created in create_ring_resources()) instead of the raw
    // decoder texture sidesteps that whole bug class, and lets the plane targets here be
    // created EAGERLY at open() time (create_ai_input_bridge()) rather than lazily.
    //
    // Never blocks present (I1/I2/I9): a cache miss (decode hasn't reached frame_num yet, or
    // it already fell out of the ~1s ring) returns {"ready": False} immediately without ever
    // touching d3d_mutex_. A cache hit takes d3d_mutex_ for a brief blit + CUDA map/copy/
    // unmap, joining the SAME already-accepted contention pattern push_ai_frame's CUDA path
    // already has with decode_loop/seek/present (see the file header: "Decode/push threads
    // are the ones who may occasionally wait a fraction of a frame for this lock, never the
    // reverse" -- this method is now one more member of that "occasionally waits" set).
    //
    // Returns a raw dict (dev_ptr as a plain uint64 CUdeviceptr, no __cuda_array_interface__/
    // DLPack machinery in C++ -- that wrapping is done Python-side, see
    // python/sumu/ai/utils/video_utils.py / the dlpack helper, per the same "avoid
    // __cuda_array_interface__/DLPack entirely in the native layer" preference spike 1 and
    // spike 3 both followed). The destination buffer (`ai_in_cu_buf_`) is a SINGLE persistent,
    // tightly-packed NV12-stacked-layout buffer reused on every call (mirrors push_ai_frame's
    // single persistent landing_tex_ in the reverse direction) -- callers must finish
    // consuming/copying it (e.g. via the ported `_nv12_to_bgr_hwc_gpu`) before the next call
    // to this method, since that call will overwrite the same memory.
    py::dict get_cuda_nv12_by_frame(int64_t frame_num)
    {
        require_open();
        UINT slot = wrap_slot(frame_num);

        // Phase 1: fast, lock-minimal cache check. On a miss -- expected to be the common
        // case whenever the AI consumer is behind decode/present (e.g. still warming up, or
        // slower than realtime) -- return immediately WITHOUT ever touching d3d_mutex_, so a
        // cold/lagging AI consumer never adds contention to decode/present/push_ai_frame.
        {
            std::lock_guard<std::mutex> lk(ready_mutex_);
            if (pt_tag_[slot] != frame_num) {
                py::dict miss;
                miss["ready"] = false;
                miss["frame_num"] = frame_num;
                return miss;
            }
        }

        // Phase 2: only reached after a phase-1 hit. Acquire d3d_mutex_, then re-check the
        // tag: between phase 1 and acquiring the lock, this slot could have been overwritten
        // (decode_loop advancing a full ring lap, or a seek()) -- both of those writers also
        // take d3d_mutex_ before touching pt_ring_tex_, so once we hold d3d_mutex_ no
        // concurrent writer can be modifying this slot's texture contents; the re-check only
        // guards against having already lost that race before we got here.
        std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
        {
            std::lock_guard<std::mutex> lk(ready_mutex_);
            if (pt_tag_[slot] != frame_num) {
                py::dict miss;
                miss["ready"] = false;
                miss["frame_num"] = frame_num;
                return miss;
            }
        }

        try {
            // Identity blit: pt_ring_tex_'s existing per-slot SRVs -> our persistent,
            // CUDA-registered plane targets (see create_ai_input_bridge()).
            D3D11_VIEWPORT vp_y{ 0.0f, 0.0f, static_cast<float>(src_width_), static_cast<float>(src_height_), 0.0f, 1.0f };
            context_->RSSetViewports(1, &vp_y);
            ID3D11RenderTargetView* rtv_y[] = { ai_in_y_rtv_.Get() };
            context_->OMSetRenderTargets(1, rtv_y, nullptr);
            context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
            context_->VSSetShader(ai_in_vs_.Get(), nullptr, 0);
            context_->PSSetShader(ai_in_ps_y_.Get(), nullptr, 0);
            ID3D11ShaderResourceView* srv_y[] = { pt_srv_y_[slot].Get() };
            context_->PSSetShaderResources(0, 1, srv_y);
            ID3D11SamplerState* samplers[] = { ai_in_sampler_.Get() };
            context_->PSSetSamplers(0, 1, samplers);
            context_->Draw(3, 0);

            D3D11_VIEWPORT vp_uv{ 0.0f, 0.0f, static_cast<float>(src_width_ / 2), static_cast<float>(src_height_ / 2), 0.0f, 1.0f };
            context_->RSSetViewports(1, &vp_uv);
            ID3D11RenderTargetView* rtv_uv[] = { ai_in_uv_rtv_.Get() };
            context_->OMSetRenderTargets(1, rtv_uv, nullptr);
            context_->PSSetShader(ai_in_ps_uv_.Get(), nullptr, 0);
            ID3D11ShaderResourceView* srv_uv[] = { pt_srv_uv_[slot].Get() };
            context_->PSSetShaderResources(0, 1, srv_uv);
            context_->Draw(3, 0);

            context_->Flush();

            // Called from whatever OS thread Python's AI-consumer thread is -- driver-API
            // calls issued directly here do not get an implicit context attach (same reason
            // push_ai_frame does this).
            check_cu(cuCtxSetCurrent(cu_ctx_), "cuCtxSetCurrent (get_cuda_nv12_by_frame)");

            CUgraphicsResource res[2] = { ai_in_cu_res_y_, ai_in_cu_res_uv_ };
            check_cu(cuGraphicsMapResources(2, res, 0), "cuGraphicsMapResources(ai_in)");

            CUarray cu_arr_y = nullptr, cu_arr_uv = nullptr;
            check_cu(cuGraphicsSubResourceGetMappedArray(&cu_arr_y, ai_in_cu_res_y_, 0, 0),
                "cuGraphicsSubResourceGetMappedArray(ai_in y)");
            check_cu(cuGraphicsSubResourceGetMappedArray(&cu_arr_uv, ai_in_cu_res_uv_, 0, 0),
                "cuGraphicsSubResourceGetMappedArray(ai_in uv)");

            // Stacked NV12 layout matching PyAV's to_ndarray('nv12') / lada's
            // _nv12_to_bgr_hwc_gpu contract: rows [0,h) = luma, rows [h, h*3/2) = interleaved
            // chroma, both at row-pitch ai_in_cu_buf_pitch_ (== src_width_, tightly packed).
            CUDA_MEMCPY2D cp_y{};
            cp_y.srcMemoryType = CU_MEMORYTYPE_ARRAY;
            cp_y.srcArray = cu_arr_y;
            cp_y.dstMemoryType = CU_MEMORYTYPE_DEVICE;
            cp_y.dstDevice = ai_in_cu_buf_;
            cp_y.dstPitch = ai_in_cu_buf_pitch_;
            cp_y.WidthInBytes = static_cast<size_t>(src_width_); // R8_UNORM: 1 byte/texel
            cp_y.Height = static_cast<size_t>(src_height_);
            check_cu(cuMemcpy2D(&cp_y), "cuMemcpy2D (ai_in Y: array -> device)");

            CUDA_MEMCPY2D cp_uv{};
            cp_uv.srcMemoryType = CU_MEMORYTYPE_ARRAY;
            cp_uv.srcArray = cu_arr_uv;
            cp_uv.dstMemoryType = CU_MEMORYTYPE_DEVICE;
            cp_uv.dstDevice = ai_in_cu_buf_ + static_cast<size_t>(src_height_) * ai_in_cu_buf_pitch_;
            cp_uv.dstPitch = ai_in_cu_buf_pitch_;
            cp_uv.WidthInBytes = static_cast<size_t>(src_width_); // R8G8_UNORM: 2 B/texel * (w/2) texels/row == w bytes
            cp_uv.Height = static_cast<size_t>(src_height_) / 2;
            check_cu(cuMemcpy2D(&cp_uv), "cuMemcpy2D (ai_in UV: array -> device)");

            check_cu(cuGraphicsUnmapResources(2, res, 0), "cuGraphicsUnmapResources(ai_in)");
        } catch (const std::exception& e) {
            HRESULT removed = device_ ? device_->GetDeviceRemovedReason() : S_OK;
            char buf[768];
            snprintf(buf, sizeof(buf), "%s [device_removed_reason=0x%08lx]", e.what(),
                static_cast<unsigned long>(removed));
            throw std::runtime_error(buf);
        }

        py::dict out;
        out["ready"] = true;
        out["dev_ptr"] = static_cast<uint64_t>(ai_in_cu_buf_);
        out["width"] = src_width_;
        out["height"] = src_height_;
        out["pitch_bytes"] = ai_in_cu_buf_pitch_;
        out["frame_num"] = frame_num;
        return out;
    }

    // ---- introspection -------------------------------------------------------------------

    double fps() const { return fps_; }
    int64_t frame_count() const { return frame_count_; }
    int64_t current_frame() const { return clock_frame_.load(std::memory_order_relaxed); }
    std::pair<int, int> dims() const { return { src_width_, src_height_ }; }

    double ai_hit_rate() const
    {
        uint64_t pc = present_count_.load(std::memory_order_relaxed);
        if (pc == 0) return 0.0;
        return static_cast<double>(n_ai_fresh_.load(std::memory_order_relaxed)) / static_cast<double>(pc);
    }

    py::dict stats()
    {
        py::dict d;
        d["fps"] = fps_;
        d["frame_count"] = frame_count_;
        d["present_count"] = present_count_.load(std::memory_order_relaxed);
        d["decode_frame_count"] = decode_frame_count_.load(std::memory_order_relaxed);
        d["ai_push_count"] = ai_push_count_.load(std::memory_order_relaxed);
        d["n_ai_fresh"] = n_ai_fresh_.load(std::memory_order_relaxed);
        d["n_ai_stale"] = n_ai_stale_.load(std::memory_order_relaxed);
        d["n_pt_fresh"] = n_pt_fresh_.load(std::memory_order_relaxed);
        d["n_pt_stale"] = n_pt_stale_.load(std::memory_order_relaxed);
        d["ai_hit_rate"] = ai_hit_rate();
        d["is_playing"] = playing_.load(std::memory_order_relaxed);
        d["current_frame"] = current_frame();
        return d;
    }

    // Present-interval (ms) median/p99/etc, computed on demand from the in-memory trace so
    // far -- safe to call while playing (trace_mutex_ guards the vectors present_loop()
    // appends to every tick).
    py::dict present_stats()
    {
        std::vector<double> intervals_ms;
        {
            std::lock_guard<std::mutex> lk(trace_mutex_);
            intervals_ms.reserve(present_qpc_ns_.size());
            for (size_t i = 1; i < present_qpc_ns_.size(); ++i)
                intervals_ms.push_back(static_cast<double>(present_qpc_ns_[i] - present_qpc_ns_[i - 1]) / 1e6);
        }
        return summarize(std::move(intervals_ms));
    }

    // trace CSV: qpc_ns,source,frame_num -- analyze_present.py (--format ns) only reads
    // column 0, so this stays compatible with the shared analysis tool while also carrying
    // the per-tick source tag for switch-point / seek-recovery analysis.
    void dump_present_trace(const std::string& path)
    {
        std::lock_guard<std::mutex> lk(trace_mutex_);
        std::ofstream f(path, std::ios::trunc);
        f << "qpc_ns,source,frame_num\n";
        for (size_t i = 0; i < present_qpc_ns_.size(); ++i) {
            f << present_qpc_ns_[i] << "," << static_cast<int>(present_source_[i]) << ","
              << present_frame_num_[i] << "\n";
        }
    }

private:
    void require_open() const
    {
        if (!opened_) throw std::runtime_error("Player.open() has not been called yet");
    }

    // ---- setup -----------------------------------------------------------------------------

    void create_window(int width_hint, int height_hint, bool maximized)
    {
        HINSTANCE hinst = GetModuleHandle(nullptr);
        WNDCLASSEXA wc{};
        wc.cbSize = sizeof(wc);
        wc.style = CS_HREDRAW | CS_VREDRAW;
        wc.lpfnWndProc = WndProc;
        wc.hInstance = hinst;
        wc.hCursor = LoadCursor(nullptr, IDC_ARROW);
        wc.lpszClassName = "Sumu_Player_WndClass";
        RegisterClassExA(&wc);

        RECT rc{ 0, 0, std::max(1, width_hint), std::max(1, height_hint) };
        AdjustWindowRect(&rc, WS_OVERLAPPEDWINDOW, FALSE);
        hwnd_ = CreateWindowExA(0, wc.lpszClassName, "sumu",
            WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT,
            rc.right - rc.left, rc.bottom - rc.top, nullptr, nullptr, hinst, nullptr);
        if (!hwnd_) throw std::runtime_error("CreateWindowEx failed");
        // Route WndProc (a free function, required by WNDCLASSEXA::lpfnWndProc) back to this
        // specific Player instance -- see the reopened-namespace WndProc definition after
        // class Player's closing brace.
        SetWindowLongPtrA(hwnd_, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(this));
        ShowWindow(hwnd_, maximized ? SW_SHOWMAXIMIZED : SW_SHOW);
        UpdateWindow(hwnd_);

        RECT client_rc;
        GetClientRect(hwnd_, &client_rc);
        win_width_ = static_cast<UINT>(std::max<LONG>(1, client_rc.right - client_rc.left));
        win_height_ = static_cast<UINT>(std::max<LONG>(1, client_rc.bottom - client_rc.top));
    }

    void create_device_and_swapchain()
    {
        D3D_FEATURE_LEVEL levels[] = { D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0 };
        D3D_FEATURE_LEVEL got{};
        HRESULT hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
            levels, ARRAYSIZE(levels), D3D11_SDK_VERSION, &device_, &got, &context_);
        check_hr(hr, "D3D11CreateDevice");

        // Present thread, decode thread, and the AI push thread (called from Python) all
        // issue calls on this same immediate context concurrently. Kept as defense-in-depth
        // alongside the explicit d3d_mutex_ (see file header) -- not a substitute for it.
        {
            ComPtr<ID3D11Multithread> mt;
            check_hr(device_.As(&mt), "QueryInterface(ID3D11Multithread)");
            mt->SetMultithreadProtected(TRUE);
        }

        ComPtr<IDXGIDevice> dxgi_device;
        device_.As(&dxgi_device);
        dxgi_device->GetAdapter(&adapter_);
        ComPtr<IDXGIFactory2> factory;
        adapter_->GetParent(IID_PPV_ARGS(&factory));

        DXGI_SWAP_CHAIN_DESC1 scd{};
        scd.Width = win_width_;
        scd.Height = win_height_;
        scd.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        scd.SampleDesc.Count = 1;
        scd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
        scd.BufferCount = 2;
        scd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
        scd.AlphaMode = DXGI_ALPHA_MODE_IGNORE;
        scd.Scaling = DXGI_SCALING_STRETCH;

        hr = factory->CreateSwapChainForHwnd(device_.Get(), hwnd_, &scd, nullptr, nullptr, &swapchain_);
        check_hr(hr, "CreateSwapChainForHwnd");
        factory->MakeWindowAssociation(hwnd_, DXGI_MWA_NO_ALT_ENTER);

        ComPtr<ID3D11Texture2D> backbuffer;
        swapchain_->GetBuffer(0, IID_PPV_ARGS(&backbuffer));
        hr = device_->CreateRenderTargetView(backbuffer.Get(), nullptr, &backbuffer_rtv_);
        check_hr(hr, "CreateRenderTargetView");
    }

    void create_shader_pipeline()
    {
        ComPtr<ID3DBlob> vs_blob, ps_nv12_blob, ps_ai_blob, err_blob;
        HRESULT hr = D3DCompile(kShaderSrc, strlen(kShaderSrc), "present.hlsl", nullptr, nullptr,
            "VSMain", "vs_5_0", 0, 0, &vs_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("VS compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        hr = D3DCompile(kShaderSrc, strlen(kShaderSrc), "present.hlsl", nullptr, nullptr,
            "PSMain_NV12", "ps_5_0", 0, 0, &ps_nv12_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("PS(NV12) compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        hr = D3DCompile(kShaderSrc, strlen(kShaderSrc), "present.hlsl", nullptr, nullptr,
            "PSMain_AI", "ps_5_0", 0, 0, &ps_ai_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("PS(AI) compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        check_hr(device_->CreateVertexShader(vs_blob->GetBufferPointer(), vs_blob->GetBufferSize(), nullptr, &vs_),
            "CreateVertexShader");
        check_hr(device_->CreatePixelShader(ps_nv12_blob->GetBufferPointer(), ps_nv12_blob->GetBufferSize(), nullptr, &ps_nv12_),
            "CreatePixelShader(NV12)");
        check_hr(device_->CreatePixelShader(ps_ai_blob->GetBufferPointer(), ps_ai_blob->GetBufferSize(), nullptr, &ps_ai_),
            "CreatePixelShader(AI)");

        D3D11_SAMPLER_DESC sd{};
        sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sd.ComparisonFunc = D3D11_COMPARISON_NEVER;
        sd.MaxLOD = D3D11_FLOAT32_MAX;
        check_hr(device_->CreateSamplerState(&sd, &sampler_), "CreateSamplerState");

        struct SliceCB { UINT arraySlice; UINT pad[3]; };
        D3D11_BUFFER_DESC cbd{};
        cbd.ByteWidth = sizeof(SliceCB);
        cbd.Usage = D3D11_USAGE_DYNAMIC;
        cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        check_hr(device_->CreateBuffer(&cbd, nullptr, &slice_cb_), "CreateBuffer(slice_cb_)");
    }

    // ---- ImGui overlay (M2: real thread split -- main-thread NewFrame/build/Render/Clone,
    // present-thread RenderDrawData-only; see ui_tick()/ui_render_drawdata() below) ---------
    //
    // init/shutdown still run on the constructor/close() thread (no present thread running
    // yet at ui_init(), already joined at ui_shutdown()).
    //
    // Backend/context-touch audit for the main-thread-NewFrame vs. present-thread-
    // RenderDrawData concurrency question (done by reading this vendored ImGui 1.92.8 tree,
    // not assumed): ImGui_ImplDX11_NewFrame() (backends/imgui_impl_dx11.cpp) only calls
    // ImGui_ImplDX11_CreateDeviceObjects() if `!bd->pVertexShader` -- since that prewarm call
    // right below already created it here in ui_init() (present thread not started yet, no
    // contention for THIS one-time call), ImGui_ImplDX11_NewFrame() on the main thread in
    // ui_tick() is a pure no-op w.r.t. the D3D11 device/context every frame after that.
    // ImGui_ImplWin32_NewFrame() only touches Win32/IO state, never D3D11. ImGui::NewFrame()/
    // ImGui::Render()/CloneOutput() are pure CPU-side ImGui-internal state (including the font
    // atlas's lazy CPU-side (re)build via UpdateTexturesNewFrame -> ImFontAtlasUpdateNewFrame,
    // which only sets an ImTextureData's status to WantCreate/WantUpdates -- it does not touch
    // ID3D11Device/Context). The ONLY ImGui call in this whole vendored tree that issues D3D11
    // device/context calls -- including the actual font-texture upload that WantCreate defers
    // to -- is ImGui_ImplDX11_RenderDrawData() (confirmed by reading its body: it maps/unmaps
    // the vertex/index buffers, iterates draw_data->Textures calling
    // ImGui_ImplDX11_UpdateTexture() for any non-OK status, and issues the Draw calls), and
    // that call is made ONLY from ui_render_drawdata() on the present thread, inside
    // d3d_mutex_, in both M1 and M2. So there is no cross-thread D3D11 context race between
    // the main thread's ui_tick() and the present thread's ui_render_drawdata() -- confirmed
    // from source, not assumed from the ImGui docs' general multi-threading caveat.
    void ui_init()
    {
        IMGUI_CHECKVERSION();
        ImGui::CreateContext();
        ImGuiIO& io = ImGui::GetIO();
        io.IniFilename = nullptr;
        ImGui::StyleColorsDark();
        ImGui_ImplWin32_Init(hwnd_);
        ImGui_ImplDX11_Init(device_.Get(), context_.Get());
        ImGui_ImplDX11_CreateDeviceObjects();
        ui_ready_ = true;
    }

    void ui_shutdown()
    {
        if (!ui_ready_) return;
        ui_ready_ = false;
        ImGui_ImplDX11_Shutdown();
        ImGui_ImplWin32_Shutdown();
        ImGui::DestroyContext();
    }

    // ---- present thread (M2): swap in the latest published snapshot, render it -------------
    //
    // Called from draw_and_present(), after the video Draw(3,0) and before Present(1,0), while
    // already holding d3d_mutex_. Never calls NewFrame/Render/CloneOutput -- only renders an
    // already-published snapshot. Tolerates ui_pending_/ui_active_ both being empty (present
    // started before the first ui_tick()) by returning without drawing anything.
    void ui_render_drawdata()
    {
        if (!ui_ready_) return;
        {
            std::lock_guard<std::mutex> lk(ui_mutex_);
            if (ui_pending_) ui_active_ = std::move(ui_pending_); // O(1) pointer move only
        }
        if (!ui_active_ || ui_active_->cmd_lists.empty()) return; // nothing published yet

        ImDrawData dd{};
        dd.Valid = true;
        dd.CmdListsCount = ui_active_->cmd_lists.Size;
        dd.TotalVtxCount = ui_active_->total_vtx;
        dd.TotalIdxCount = ui_active_->total_idx;
        dd.DisplayPos = ui_active_->display_pos;
        dd.DisplaySize = ui_active_->display_size;
        dd.FramebufferScale = ui_active_->framebuffer_scale;
        dd.Textures = &ImGui::GetPlatformIO().Textures; // font-texture WantCreate/WantUpdates
                                                          // list lives on the (single, shared)
                                                          // ImGuiContext, not per-snapshot.
        dd.CmdLists.swap(ui_active_->cmd_lists); // O(1) borrow, no per-frame allocation
        ImGui_ImplDX11_RenderDrawData(&dd);
        dd.CmdLists.swap(ui_active_->cmd_lists); // give ownership back to the snapshot
    }

    // ---- product UI (M3) -- built on the main thread inside ui_tick(), between NewFrame()
    // and Render(). Only RECORDS intents (record_toggle_play()/record_seek()/ui_intents_.* on
    // Apply) -- never calls play()/pause()/seek()/anything that touches transport or scheduler
    // config directly. Python's main thread is the sole executor (see take_ui_intents() and
    // scripts/run_player.py).
    void build_ui()
    {
        float top_bar_h = 0.0f;
        build_top_bar(top_bar_h);
        if (ui_settings_open_) build_settings_panel(top_bar_h);
        build_bottom_bar();
    }

    void build_top_bar(float& out_height)
    {
        ImGuiIO& io = ImGui::GetIO();
        const float bar_h = 32.0f;
        out_height = bar_h;

        ImGui::SetNextWindowPos(ImVec2(0, 0));
        ImGui::SetNextWindowSize(ImVec2(io.DisplaySize.x, bar_h));
        ImGuiWindowFlags flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |
            ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoBringToFrontOnFocus;
        ImGui::Begin("##sumu_top_bar", nullptr, flags);

        if (ImGui::Button(ui_settings_open_ ? "[x] Settings" : "[ ] Settings")) {
            ui_settings_open_ = !ui_settings_open_;
            if (ui_settings_open_) settings_edit_init_ = false; // resync edit buffers to latest cfg on open
        }
        ImGui::SameLine();
        ImGui::TextUnformatted(basename_of(video_path_).c_str());
        ImGui::SameLine();

        // Blank draggable region (native-titlebar-like drag), sized to leave room for the
        // four right-side buttons so it doesn't eat their clicks.
        const float btn_w = 28.0f;
        const int n_btns = 4; // minimize, maximize/restore, fullscreen, close
        float drag_w = ImGui::GetContentRegionAvail().x - (btn_w + ImGui::GetStyle().ItemSpacing.x) * n_btns;
        if (drag_w < 0.0f) drag_w = 0.0f;
        ImGui::InvisibleButton("##drag_region", ImVec2(drag_w, bar_h - 4.0f));
        if (ImGui::IsItemHovered() && ImGui::IsMouseClicked(ImGuiMouseButton_Left)) {
            ReleaseCapture();
            SendMessageA(hwnd_, WM_NCLBUTTONDOWN, HTCAPTION, 0);
        }
        ImGui::SameLine();

        if (ImGui::Button("_", ImVec2(btn_w, 0))) {
            ShowWindow(hwnd_, SW_MINIMIZE);
        }
        ImGui::SameLine();
        bool zoomed = IsZoomed(hwnd_) != 0;
        if (ImGui::Button(zoomed ? "[]" : "[ ]", ImVec2(btn_w, 0))) {
            ShowWindow(hwnd_, zoomed ? SW_RESTORE : SW_MAXIMIZE);
        }
        ImGui::SameLine();
        if (ImGui::Button("[F]", ImVec2(btn_w, 0))) {
            toggle_fullscreen();
        }
        ImGui::SameLine();
        if (ImGui::Button("X", ImVec2(btn_w, 0))) {
            PostMessageA(hwnd_, WM_CLOSE, 0, 0);
        }

        ImGui::End();
    }

    // Auto-hides when the mouse leaves the bottom ~15% of the client area (simple mouse-Y-zone
    // check, per the task brief). Self-drawn progress bar (InvisibleButton + ImDrawList, not
    // SliderInt): click/drag -> frame_for_seekbar_x() -> record_seek(); playhead position ->
    // seekbar_x_for_frame(current_frame()).
    void build_bottom_bar()
    {
        ImGuiIO& io = ImGui::GetIO();
        const float bar_h = 56.0f;
        const float show_zone_y = io.DisplaySize.y * 0.85f;
        bool mouse_in_zone = io.MousePos.y >= show_zone_y && io.MousePos.y <= io.DisplaySize.y &&
            io.MousePos.x >= 0.0f && io.MousePos.x <= io.DisplaySize.x;
        if (!mouse_in_zone) return; // auto-hide

        ImGui::SetNextWindowPos(ImVec2(0, io.DisplaySize.y - bar_h));
        ImGui::SetNextWindowSize(ImVec2(io.DisplaySize.x, bar_h));
        ImGuiWindowFlags flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |
            ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoBringToFrontOnFocus;
        ImGui::Begin("##sumu_bottom_bar", nullptr, flags);

        if (ImGui::Button(is_playing() ? "Pause" : "Play", ImVec2(56.0f, 0))) {
            record_toggle_play();
        }
        ImGui::SameLine();

        int64_t fc = frame_count();
        double fpsv = fps() > 0.0 ? fps() : 1.0;
        ImGui::TextUnformatted(format_mmss(static_cast<double>(current_frame()) / fpsv).c_str());
        ImGui::SameLine();

        // Reserve space for the trailing total-duration label so the track sizes itself first.
        std::string total_str = format_mmss(static_cast<double>(std::max<int64_t>(fc - 1, 0)) / fpsv);
        float total_w = ImGui::CalcTextSize(total_str.c_str()).x;
        float track_w = ImGui::GetContentRegionAvail().x - total_w - ImGui::GetStyle().ItemSpacing.x;
        if (track_w < 10.0f) track_w = 10.0f;
        const float track_h = 18.0f;

        ImVec2 track_pos = ImGui::GetCursorScreenPos();
        ImGui::InvisibleButton("##seekbar", ImVec2(track_w, track_h));
        bool track_active = ImGui::IsItemActive();
        bool track_hovered = ImGui::IsItemHovered();
        float x0 = track_pos.x;
        float x1 = track_pos.x + track_w;
        float bar_y = track_pos.y + track_h * 0.5f;

        if (track_active) { // covers both the initial click and continued dragging
            int64_t target = frame_for_seekbar_x(ImGui::GetIO().MousePos.x, x0, x1, fc);
            record_seek(target);
        }

        ImDrawList* dl = ImGui::GetWindowDrawList();
        dl->AddRectFilled(ImVec2(x0, bar_y - 2.0f), ImVec2(x1, bar_y + 2.0f), IM_COL32(90, 90, 90, 255));
        float played_x = seekbar_x_for_frame(current_frame(), x0, x1, fc);
        dl->AddRectFilled(ImVec2(x0, bar_y - 2.0f), ImVec2(played_x, bar_y + 2.0f), IM_COL32(200, 200, 60, 255));
        dl->AddCircleFilled(ImVec2(played_x, bar_y), 5.0f, IM_COL32(230, 230, 230, 255));

        if (track_hovered || track_active) {
            float hx = std::clamp(ImGui::GetIO().MousePos.x, x0, x1);
            dl->AddLine(ImVec2(hx, track_pos.y - 4.0f), ImVec2(hx, track_pos.y + track_h + 4.0f),
                IM_COL32(255, 255, 255, 160));

            ID3D11ShaderResourceView* thumb = get_thumbnail(frame_for_seekbar_x(hx, x0, x1, fc));
            if (thumb) { // M3: get_thumbnail() always returns nullptr -- this branch is dead
                         // until M4 implements it, kept so the hook's call site is real code.
                ImVec2 tsize(160.0f, 90.0f);
                ImVec2 tmin(std::clamp(hx - tsize.x * 0.5f, x0, x1 - tsize.x), track_pos.y - 12.0f - tsize.y);
                dl->AddImage(thumb, tmin, ImVec2(tmin.x + tsize.x, tmin.y + tsize.y));
            }
        }

        ImGui::SameLine();
        ImGui::TextUnformatted(total_str.c_str());

        ImGui::End();
    }

    void build_settings_panel(float top_bar_h)
    {
        ImGuiIO& io = ImGui::GetIO();
        const float panel_w = 260.0f;
        ImGui::SetNextWindowPos(ImVec2(0, top_bar_h));
        ImGui::SetNextWindowSize(ImVec2(panel_w, io.DisplaySize.y - top_bar_h));
        ImGuiWindowFlags flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoCollapse;
        ImGui::Begin("##sumu_settings", nullptr, flags);

        // Staged locally in settings_edit_*_, seeded from the Python-refreshed ui_cfg_*
        // mirror only once per open (not every frame -- that would clobber an in-progress
        // edit with Python's per-tick refresh of the ACTUAL committed config).
        if (!settings_edit_init_) {
            settings_edit_clip_length_ = ui_cfg_clip_length_;
            settings_edit_max_regions_ = ui_cfg_max_regions_;
            settings_edit_init_ = true;
        }

        ImGui::TextUnformatted("Settings");
        ImGui::Separator();
        ImGui::SliderInt("Clip length", &settings_edit_clip_length_, 1, 180);
        ImGui::SliderInt("Max regions/frame", &settings_edit_max_regions_, 1, 8);
        if (ImGui::Button("Apply")) {
            // Only committed into ui_intents_ here -- Python only rebuilds the (expensive)
            // scheduler when it sees a non-null clip_length/max_regions, never on every slider
            // tick.
            ui_intents_.clip_length = settings_edit_clip_length_;
            ui_intents_.max_regions = settings_edit_max_regions_;
        }

        ImGui::Separator();
        ImGui::TextUnformatted("Diagnostics");
        ImGui::Text("AI hit rate: %.3f", ai_hit_rate());
        // backlog_resyncs / clips_restored / frames_pushed are Python Scheduler.get_stats()
        // fields (python/sumu/scheduler.py) with no native equivalent in Player::stats() and no
        // channel carrying them into native -- intentionally not displayed here rather than
        // fabricated (flagged in this milestone's report as a plan-vs-code gap).

        ImGui::End();
    }

    // Borderless fill-monitor fullscreen toggle -- explicitly NOT exclusive fullscreen (no mode
    // change, no Alt+Enter path; WM_SYSKEYDOWN already swallows Alt+Enter, see WndProc).
    void toggle_fullscreen()
    {
        if (!fullscreen_) {
            GetWindowRect(hwnd_, &windowed_rect_);
            windowed_style_ = GetWindowLongA(hwnd_, GWL_STYLE);

            HMONITOR mon = MonitorFromWindow(hwnd_, MONITOR_DEFAULTTONEAREST);
            MONITORINFO mi{ sizeof(mi) };
            GetMonitorInfo(mon, &mi);

            SetWindowLongA(hwnd_, GWL_STYLE, windowed_style_ & ~(WS_CAPTION | WS_THICKFRAME |
                WS_MINIMIZEBOX | WS_MAXIMIZEBOX | WS_SYSMENU));
            SetWindowPos(hwnd_, HWND_TOP, mi.rcMonitor.left, mi.rcMonitor.top,
                mi.rcMonitor.right - mi.rcMonitor.left, mi.rcMonitor.bottom - mi.rcMonitor.top,
                SWP_FRAMECHANGED | SWP_NOOWNERZORDER);
            fullscreen_ = true;
        } else {
            SetWindowLongA(hwnd_, GWL_STYLE, windowed_style_);
            SetWindowPos(hwnd_, nullptr, windowed_rect_.left, windowed_rect_.top,
                windowed_rect_.right - windowed_rect_.left, windowed_rect_.bottom - windowed_rect_.top,
                SWP_FRAMECHANGED | SWP_NOOWNERZORDER | SWP_NOZORDER);
            fullscreen_ = false;
        }
    }

    // M4 hook (not implemented here): scrub thumbnail SRV for a given content frame number, or
    // nullptr if unavailable. M3 always returns nullptr -- a real implementation needs its own
    // scrub-decode path INSIDE this Player (never a second Player instance: native's g_quit is
    // a process-global shared across instances, see the file header -- a second instance would
    // cause accidental quits).
    ID3D11ShaderResourceView* get_thumbnail(int64_t frame_num)
    {
        (void)frame_num;
        return nullptr;
    }

    void create_ring_resources()
    {
        D3D11_TEXTURE2D_DESC pt_desc{};
        pt_desc.Width = src_width_;
        pt_desc.Height = src_height_;
        pt_desc.MipLevels = 1;
        pt_desc.ArraySize = kRingCapacity;
        pt_desc.Format = DXGI_FORMAT_NV12;
        pt_desc.SampleDesc.Count = 1;
        pt_desc.Usage = D3D11_USAGE_DEFAULT;
        // NV12 is a video format; on this driver CreateTexture2D rejects it (E_INVALIDARG)
        // with BIND_SHADER_RESOURCE alone -- matching the decoder's own hw_frames_ctx bind
        // flags (BIND_DECODER | BIND_SHADER_RESOURCE) makes it succeed. We never actually
        // use this as a decode target, just as a same-format GPU-side copy destination + SRV
        // source.
        pt_desc.BindFlags = D3D11_BIND_DECODER | D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&pt_desc, nullptr, &pt_ring_tex_), "CreateTexture2D(pt_ring_tex_)");

        pt_srv_y_.resize(kRingCapacity);
        pt_srv_uv_.resize(kRingCapacity);
        for (UINT i = 0; i < kRingCapacity; ++i) {
            D3D11_SHADER_RESOURCE_VIEW_DESC yd{};
            yd.Format = DXGI_FORMAT_R8_UNORM;
            yd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2DARRAY;
            yd.Texture2DArray.MostDetailedMip = 0;
            yd.Texture2DArray.MipLevels = 1;
            yd.Texture2DArray.FirstArraySlice = i;
            yd.Texture2DArray.ArraySize = 1;
            check_hr(device_->CreateShaderResourceView(pt_ring_tex_.Get(), &yd, &pt_srv_y_[i]), "CreateSRV(pt Y)");

            D3D11_SHADER_RESOURCE_VIEW_DESC uvd = yd;
            uvd.Format = DXGI_FORMAT_R8G8_UNORM;
            check_hr(device_->CreateShaderResourceView(pt_ring_tex_.Get(), &uvd, &pt_srv_uv_[i]), "CreateSRV(pt UV)");
        }

        D3D11_TEXTURE2D_DESC ai_desc{};
        ai_desc.Width = src_width_;
        ai_desc.Height = src_height_;
        ai_desc.MipLevels = 1;
        ai_desc.ArraySize = kRingCapacity;
        ai_desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        ai_desc.SampleDesc.Count = 1;
        ai_desc.Usage = D3D11_USAGE_DEFAULT;
        ai_desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&ai_desc, nullptr, &ai_ring_tex_), "CreateTexture2D(ai_ring_tex_)");

        ai_srv_.resize(kRingCapacity);
        for (UINT i = 0; i < kRingCapacity; ++i) {
            D3D11_SHADER_RESOURCE_VIEW_DESC ad{};
            ad.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
            ad.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2DARRAY;
            ad.Texture2DArray.MostDetailedMip = 0;
            ad.Texture2DArray.MipLevels = 1;
            ad.Texture2DArray.FirstArraySlice = i;
            ad.Texture2DArray.ArraySize = 1;
            check_hr(device_->CreateShaderResourceView(ai_ring_tex_.Get(), &ad, &ai_srv_[i]), "CreateSRV(ai)");
        }
    }

    void create_landing_texture()
    {
        D3D11_TEXTURE2D_DESC td{};
        td.Width = src_width_;
        td.Height = src_height_;
        td.MipLevels = 1;
        td.ArraySize = 1;
        td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        td.SampleDesc.Count = 1;
        td.Usage = D3D11_USAGE_DEFAULT;
        td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&td, nullptr, &landing_tex_), "CreateTexture2D(landing_tex_)");
    }

    void init_cuda_driver()
    {
        check_cu(cuInit(0), "cuInit");
        check_cu(cuDeviceGet(&cu_dev_, 0), "cuDeviceGet");

        CUdevice dev_from_adapter = -1;
        CUresult r = cuD3D11GetDevice(&dev_from_adapter, adapter_.Get());
        if (r != CUDA_SUCCESS || dev_from_adapter != cu_dev_) {
            char buf[256];
            snprintf(buf, sizeof(buf),
                "cuD3D11GetDevice mismatch: D3D adapter maps to CUDA device %d, expected %d (CUresult=%d)",
                (int)dev_from_adapter, (int)cu_dev_, (int)r);
            throw std::runtime_error(buf);
        }

        check_cu(cuDevicePrimaryCtxRetain(&cu_ctx_, cu_dev_), "cuDevicePrimaryCtxRetain");
        check_cu(cuCtxSetCurrent(cu_ctx_), "cuCtxSetCurrent");
    }

    void register_landing_with_cuda()
    {
        check_cu(cuGraphicsD3D11RegisterResource(&cu_res_, landing_tex_.Get(), CU_GRAPHICS_REGISTER_FLAGS_NONE),
            "cuGraphicsD3D11RegisterResource");
    }

    // ---- AI input bridge setup (additive, Part B; see get_cuda_nv12_by_frame's header
    // comment for the full design rationale) --------------------------------------------
    void create_ai_input_bridge()
    {
        // Own small shader program for the identity blit, compiled inline (NOT routed
        // through native/cmake/embed_shader.cmake's present.hlsl pipeline -- that stays
        // exactly as promoted/validated; this is a separate, additive program).
        ComPtr<ID3DBlob> vs_blob, ps_y_blob, ps_uv_blob, err_blob;
        HRESULT hr = D3DCompile(kAiInputBlitShaderSrc, strlen(kAiInputBlitShaderSrc), "ai_input_blit.hlsl",
            nullptr, nullptr, "VSMain", "vs_5_0", 0, 0, &vs_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("AI-input VS compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));
        hr = D3DCompile(kAiInputBlitShaderSrc, strlen(kAiInputBlitShaderSrc), "ai_input_blit.hlsl",
            nullptr, nullptr, "PSMain_Y", "ps_5_0", 0, 0, &ps_y_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("AI-input PS(Y) compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));
        hr = D3DCompile(kAiInputBlitShaderSrc, strlen(kAiInputBlitShaderSrc), "ai_input_blit.hlsl",
            nullptr, nullptr, "PSMain_UV", "ps_5_0", 0, 0, &ps_uv_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("AI-input PS(UV) compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        check_hr(device_->CreateVertexShader(vs_blob->GetBufferPointer(), vs_blob->GetBufferSize(), nullptr, &ai_in_vs_),
            "CreateVertexShader(ai_in)");
        check_hr(device_->CreatePixelShader(ps_y_blob->GetBufferPointer(), ps_y_blob->GetBufferSize(), nullptr, &ai_in_ps_y_),
            "CreatePixelShader(ai_in Y)");
        check_hr(device_->CreatePixelShader(ps_uv_blob->GetBufferPointer(), ps_uv_blob->GetBufferSize(), nullptr, &ai_in_ps_uv_),
            "CreatePixelShader(ai_in UV)");

        D3D11_SAMPLER_DESC sd{};
        sd.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT; // exact 1:1 texel identity copy, no filtering
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sd.ComparisonFunc = D3D11_COMPARISON_NEVER;
        sd.MaxLOD = D3D11_FLOAT32_MAX;
        check_hr(device_->CreateSamplerState(&sd, &ai_in_sampler_), "CreateSamplerState(ai_in)");

        // Sized to src_width_/src_height_ -- the DISPLAY size, matching pt_ring_tex_ itself.
        // Unlike spike3 (which blitted straight off the decoder's own macroblock-padded
        // hw_frames_ctx texture and needed a lazy real-size probe, see
        // docs/spike3_nv12_interop.md), pt_ring_tex_ has ALREADY been cropped to display size
        // by decode_loop()'s/seek()'s own CopySubresourceRegion (existing, unmodified code)
        // -- so these targets can be created eagerly, right here, with no padding concern.
        D3D11_TEXTURE2D_DESC yd{};
        yd.Width = static_cast<UINT>(src_width_);
        yd.Height = static_cast<UINT>(src_height_);
        yd.MipLevels = 1;
        yd.ArraySize = 1;
        yd.Format = DXGI_FORMAT_R8_UNORM;
        yd.SampleDesc.Count = 1;
        yd.Usage = D3D11_USAGE_DEFAULT;
        yd.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&yd, nullptr, &ai_in_y_tex_), "CreateTexture2D(ai_in_y_tex_)");
        check_hr(device_->CreateRenderTargetView(ai_in_y_tex_.Get(), nullptr, &ai_in_y_rtv_), "CreateRTV(ai_in_y)");

        D3D11_TEXTURE2D_DESC uvd = yd;
        uvd.Width = static_cast<UINT>(src_width_) / 2;
        uvd.Height = static_cast<UINT>(src_height_) / 2;
        uvd.Format = DXGI_FORMAT_R8G8_UNORM;
        check_hr(device_->CreateTexture2D(&uvd, nullptr, &ai_in_uv_tex_), "CreateTexture2D(ai_in_uv_tex_)");
        check_hr(device_->CreateRenderTargetView(ai_in_uv_tex_.Get(), nullptr, &ai_in_uv_rtv_), "CreateRTV(ai_in_uv)");

        check_cu(cuGraphicsD3D11RegisterResource(&ai_in_cu_res_y_, ai_in_y_tex_.Get(), CU_GRAPHICS_REGISTER_FLAGS_NONE),
            "cuGraphicsD3D11RegisterResource(ai_in_y_tex_)");
        check_cu(cuGraphicsD3D11RegisterResource(&ai_in_cu_res_uv_, ai_in_uv_tex_.Get(), CU_GRAPHICS_REGISTER_FLAGS_NONE),
            "cuGraphicsD3D11RegisterResource(ai_in_uv_tex_)");

        // Persistent, tightly-packed CUDA destination buffer (stacked NV12 layout, see
        // get_cuda_nv12_by_frame()). Tightly packed (pitch == src_width_) so the Python-side
        // DLPack wrap can describe it as a contiguous tensor (NULL strides).
        ai_in_cu_buf_pitch_ = static_cast<size_t>(src_width_);
        ai_in_cu_buf_size_ = ai_in_cu_buf_pitch_ * static_cast<size_t>(src_height_) * 3 / 2;
        check_cu(cuMemAlloc(&ai_in_cu_buf_, ai_in_cu_buf_size_), "cuMemAlloc(ai_in_cu_buf_)");
    }

    // ---- decode thread -----------------------------------------------------------------------

    void decode_loop()
    {
        while (!stop_.load(std::memory_order_relaxed)) {
            // Throttle: never get more than kDecodeAheadMax frames ahead of the present
            // head, so we never overwrite a ring slot before present has had its one chance
            // to read it. Before the present thread has started, present_head_frame_ is
            // whatever open() initialized it to (0); after a seek it's the seeked frame.
            for (;;) {
                if (stop_.load(std::memory_order_relaxed)) return;
                int64_t head = present_head_frame_.load(std::memory_order_relaxed);
                int64_t high = pt_high_water_.load(std::memory_order_relaxed);
                if (high - head < kDecodeAheadMax) break;
                Sleep(1);
            }

            // Widened critical section (see file header): decode-one-frame + copy-into-ring
            // + tag-ready is one atomic unit with respect to seek()'s own reposition, so a
            // frame decoded from the OLD position can never land in the ring after a seek's
            // fresh write to the same slot.
            std::lock_guard<std::mutex> decoder_lock(decoder_mutex_);
            if (stop_.load(std::memory_order_relaxed)) return;

            DecodedFrame df;
            if (!decoder_.next_frame(df)) {
                // Unrecoverable decode error. Stop the whole run rather than spin; present
                // thread will keep re-presenting the last good frame forever via the
                // stale-fallback path rather than hitching.
                stop_.store(true, std::memory_order_relaxed);
                return;
            }

            int64_t frame_num = static_cast<int64_t>(std::llround(df.pts_seconds * fps_));
            UINT slot = wrap_slot(frame_num);

            {
                std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
                context_->CopySubresourceRegion(pt_ring_tex_.Get(), slot, 0, 0, 0,
                    df.texture, df.array_slice, nullptr);
            }
            {
                std::lock_guard<std::mutex> lk(ready_mutex_);
                pt_tag_[slot] = frame_num;
            }
            pt_high_water_.store(frame_num, std::memory_order_relaxed);
            ++decode_frame_count_;
        }
    }

    // ---- present thread ------------------------------------------------------------------------

    void present_loop()
    {
        const double ticks_per_ms = static_cast<double>(freq_.QuadPart) / 1000.0;
        int64_t last_frame_local = -1;
        Source last_actual_source = Source::PassthroughFresh;
        UINT last_actual_slot = 0;
        uint64_t local_seek_version = seek_version_.load(std::memory_order_relaxed);
        int64_t tick_idx = 0;

        {
            std::lock_guard<std::mutex> lk(trace_mutex_);
            present_qpc_ns_.reserve(1u << 16);
            present_source_.reserve(1u << 16);
            present_frame_num_.reserve(1u << 16);
        }

        while (!stop_.load(std::memory_order_relaxed)) {
            // Pacing engine: fixed cadence at fps_, independent of play/pause/seek state so
            // this thread never busy-spins and never needs tearing down/rebuilding across
            // transport changes.
            ++tick_idx;
            LARGE_INTEGER target_qpc;
            target_qpc.QuadPart = pace_origin_qpc_.QuadPart +
                static_cast<LONGLONG>(static_cast<double>(tick_idx) / fps_ * freq_.QuadPart);
            if (!wait_until_qpc_or_stop(target_qpc, ticks_per_ms)) break;

            uint64_t sv = seek_version_.load(std::memory_order_relaxed);
            bool just_seeked = (sv != local_seek_version);
            local_seek_version = sv;

            if (just_seeked) {
                // Bypass the monotonic guard below for exactly this tick (a seek can
                // legitimately move backward or far forward), and repoint the stale-repeat
                // fallback at the freshly-seeked slot so an immediately-following tick that
                // races ahead of decode never repeats pre-seek content.
                last_actual_slot = static_cast<UINT>(seek_slot_hint_.load(std::memory_order_relaxed));
                last_actual_source = Source::PassthroughFresh;
            }

            int64_t frame;
            if (playing_.load(std::memory_order_relaxed)) {
                LARGE_INTEGER now;
                QueryPerformanceCounter(&now);
                int64_t aq = anchor_qpc_ticks_.load(std::memory_order_relaxed);
                int64_t af = anchor_frame_.load(std::memory_order_relaxed);
                double elapsed_s = static_cast<double>(now.QuadPart - aq) / freq_.QuadPart;
                int64_t computed = af + static_cast<int64_t>(std::llround(elapsed_s * fps_));
                if (!just_seeked && computed <= last_frame_local) computed = last_frame_local + 1;
                frame = computed;
            } else {
                // Paused: frozen at anchor_frame_, present thread keeps redrawing it so the
                // heartbeat (present cadence) never stops even though content doesn't advance.
                frame = anchor_frame_.load(std::memory_order_relaxed);
            }
            last_frame_local = frame;
            clock_frame_.store(frame, std::memory_order_relaxed);
            present_head_frame_.store(frame, std::memory_order_relaxed);

            UINT slot = wrap_slot(frame);
            Source source;
            UINT use_slot;
            {
                std::lock_guard<std::mutex> lk(ready_mutex_);
                if (ai_tag_[slot] == frame) {
                    source = Source::AiFresh;
                    use_slot = slot;
                } else if (pt_tag_[slot] == frame) {
                    source = Source::PassthroughFresh;
                    use_slot = slot;
                } else {
                    // Neither map has this exact frame number ready. NEVER block -- just
                    // re-present whatever was actually shown last tick (I2/I9).
                    source = is_ai(last_actual_source) ? Source::AiStale : Source::PassthroughStale;
                    use_slot = last_actual_slot;
                }
            }

            {
                // Serializes ALL D3D11/CUDA-interop use of the shared context (see file
                // header). Decode/push threads are the ones who may occasionally wait a
                // fraction of a frame for this lock, never the reverse.
                std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
                draw_and_present(source, use_slot);
            }

            LARGE_INTEGER pres_now;
            QueryPerformanceCounter(&pres_now);
            {
                std::lock_guard<std::mutex> lk(trace_mutex_);
                present_qpc_ns_.push_back(qpc_to_ns(pres_now));
                present_source_.push_back(static_cast<int8_t>(source));
                present_frame_num_.push_back(frame);
            }
            present_count_.fetch_add(1, std::memory_order_relaxed);
            switch (source) {
            case Source::AiFresh: n_ai_fresh_.fetch_add(1, std::memory_order_relaxed); break;
            case Source::AiStale: n_ai_stale_.fetch_add(1, std::memory_order_relaxed); break;
            case Source::PassthroughFresh: n_pt_fresh_.fetch_add(1, std::memory_order_relaxed); break;
            case Source::PassthroughStale: n_pt_stale_.fetch_add(1, std::memory_order_relaxed); break;
            }

            if (source == Source::AiFresh || source == Source::PassthroughFresh) {
                last_actual_source = source;
                last_actual_slot = use_slot;
            }
        }
    }

    void draw_and_present(Source source, UINT slot)
    {
        context_->OMSetBlendState(nullptr, nullptr, 0xffffffff);

        D3D11_VIEWPORT vp{ 0.0f, 0.0f, static_cast<float>(win_width_), static_cast<float>(win_height_), 0.0f, 1.0f };
        context_->RSSetViewports(1, &vp);
        ID3D11RenderTargetView* rtvs[] = { backbuffer_rtv_.Get() };
        context_->OMSetRenderTargets(1, rtvs, nullptr);
        context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        context_->VSSetShader(vs_.Get(), nullptr, 0);

        struct SliceCB { UINT arraySlice; UINT pad[3]; };
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (SUCCEEDED(context_->Map(slice_cb_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
            SliceCB cb{ slot, {0, 0, 0} };
            memcpy(mapped.pData, &cb, sizeof(cb));
            context_->Unmap(slice_cb_.Get(), 0);
        }
        ID3D11Buffer* cbs[] = { slice_cb_.Get() };
        context_->PSSetConstantBuffers(0, 1, cbs);
        ID3D11SamplerState* samplers[] = { sampler_.Get() };
        context_->PSSetSamplers(0, 1, samplers);

        if (is_ai(source)) {
            context_->PSSetShader(ps_ai_.Get(), nullptr, 0);
            ID3D11ShaderResourceView* srvs[] = { ai_srv_[slot].Get() };
            context_->PSSetShaderResources(2, 1, srvs);
        } else {
            context_->PSSetShader(ps_nv12_.Get(), nullptr, 0);
            ID3D11ShaderResourceView* srvs[] = { pt_srv_y_[slot].Get(), pt_srv_uv_[slot].Get() };
            context_->PSSetShaderResources(0, 2, srvs);
        }

        context_->Draw(3, 0);

        // M2: present thread only renders an already-published draw-data snapshot (built on
        // the main thread by ui_tick()) -- see ui_render_drawdata()'s header comment. Called
        // here, after the video Draw(3,0) and before Present(1,0), still inside d3d_mutex_.
        ui_render_drawdata();

        swapchain_->Present(1, 0);
    }

    // ---- helpers -----------------------------------------------------------------------------

    static UINT wrap_slot(int64_t frame_num)
    {
        int64_t m = frame_num % static_cast<int64_t>(kRingCapacity);
        if (m < 0) m += kRingCapacity;
        return static_cast<UINT>(m);
    }

    static double qpc_freq_d()
    {
        LARGE_INTEGER f;
        QueryPerformanceFrequency(&f);
        return static_cast<double>(f.QuadPart);
    }

    static int64_t qpc_to_ns(LARGE_INTEGER c)
    {
        double ns_per_tick = 1e9 / qpc_freq_d();
        return static_cast<int64_t>(static_cast<double>(c.QuadPart) * ns_per_tick + 0.5);
    }

    // Hybrid sleep+spin wait (same strategy as spike 0/2), periodically checking stop_ so
    // close() doesn't have to wait out a full frame interval. Returns false if stop was
    // requested before the deadline.
    bool wait_until_qpc_or_stop(LARGE_INTEGER target, double ticks_per_ms)
    {
        LARGE_INTEGER now;
        for (;;) {
            if (stop_.load(std::memory_order_relaxed)) return false;
            QueryPerformanceCounter(&now);
            double remaining_ms = static_cast<double>(target.QuadPart - now.QuadPart) / ticks_per_ms;
            if (remaining_ms <= 0.0) return true;
            if (remaining_ms > 2.0) {
                Sleep(static_cast<DWORD>(std::min(remaining_ms - 1.0, 5.0)));
            } else {
                YieldProcessor();
            }
        }
    }

    // ---- state -------------------------------------------------------------------------------

    int src_width_ = 0;
    int src_height_ = 0;
    UINT win_width_ = 0;
    UINT win_height_ = 0;
    HWND hwnd_ = nullptr;
    bool timer_period_set_ = false;
    bool closed_ = false;
    bool opened_ = false;
    bool ui_ready_ = false;

    // ---- UI draw-data handoff (M2) -- ui_pending_ is main-thread-written/present-moved-out,
    // ui_active_ is present-thread-exclusive (never touched under ui_mutex_ once moved into).
    // ui_mutex_ is only ever held for the O(1) pointer move in ui_tick()/ui_render_drawdata(),
    // never across RenderDrawData -- see UiDrawSnapshot's header comment and both methods.
    std::mutex ui_mutex_;
    std::unique_ptr<UiDrawSnapshot> ui_pending_;
    std::unique_ptr<UiDrawSnapshot> ui_active_;

    // ---- UI product state (M3) -- main-thread-exclusive, see UiIntents' header comment. ------
    std::string video_path_;
    UiIntents ui_intents_;
    int ui_cfg_clip_length_ = 30; // Python-refreshed mirror of the ACTUAL committed config,
    int ui_cfg_max_regions_ = 1;  // shown read-only in the settings panel until Apply.
    bool ui_settings_open_ = false;
    bool settings_edit_init_ = false;    // one-shot: (re)seed edit buffers from ui_cfg_* the
    int settings_edit_clip_length_ = 30; // moment the settings panel is opened, so an
    int settings_edit_max_regions_ = 1;  // in-progress edit survives Python's per-tick refresh.
    bool fullscreen_ = false;
    RECT windowed_rect_{};  // saved pre-fullscreen window rect, for restore
    LONG windowed_style_ = 0; // saved pre-fullscreen GWL_STYLE, for restore

    ComPtr<ID3D11Device> device_;
    ComPtr<ID3D11DeviceContext> context_;
    ComPtr<IDXGIAdapter> adapter_;
    ComPtr<IDXGISwapChain1> swapchain_;
    ComPtr<ID3D11RenderTargetView> backbuffer_rtv_;
    ComPtr<ID3D11VertexShader> vs_;
    ComPtr<ID3D11PixelShader> ps_nv12_;
    ComPtr<ID3D11PixelShader> ps_ai_;
    ComPtr<ID3D11SamplerState> sampler_;
    ComPtr<ID3D11Buffer> slice_cb_;

    ComPtr<ID3D11Texture2D> pt_ring_tex_;
    std::vector<ComPtr<ID3D11ShaderResourceView>> pt_srv_y_;
    std::vector<ComPtr<ID3D11ShaderResourceView>> pt_srv_uv_;
    std::vector<int64_t> pt_tag_; // guarded by ready_mutex_
    std::atomic<int64_t> pt_high_water_{ -1 };

    ComPtr<ID3D11Texture2D> ai_ring_tex_;
    std::vector<ComPtr<ID3D11ShaderResourceView>> ai_srv_;
    std::vector<int64_t> ai_tag_; // guarded by ready_mutex_

    ComPtr<ID3D11Texture2D> landing_tex_;
    CUdevice cu_dev_ = 0;
    CUcontext cu_ctx_ = nullptr;
    CUgraphicsResource cu_res_ = nullptr;

    // ---- AI input bridge state (additive, Part B) -- see create_ai_input_bridge() and
    // get_cuda_nv12_by_frame(). All D3D11/CUDA-interop touches of these go through
    // d3d_mutex_, same as the rest of the shared device/context (file header).
    ComPtr<ID3D11VertexShader> ai_in_vs_;
    ComPtr<ID3D11PixelShader> ai_in_ps_y_;
    ComPtr<ID3D11PixelShader> ai_in_ps_uv_;
    ComPtr<ID3D11SamplerState> ai_in_sampler_;
    ComPtr<ID3D11Texture2D> ai_in_y_tex_;
    ComPtr<ID3D11RenderTargetView> ai_in_y_rtv_;
    ComPtr<ID3D11Texture2D> ai_in_uv_tex_;
    ComPtr<ID3D11RenderTargetView> ai_in_uv_rtv_;
    CUgraphicsResource ai_in_cu_res_y_ = nullptr;
    CUgraphicsResource ai_in_cu_res_uv_ = nullptr;
    CUdeviceptr ai_in_cu_buf_ = 0;   // persistent, single-slot, tightly-packed NV12 dest buffer
    size_t ai_in_cu_buf_pitch_ = 0;  // == src_width_ (tightly packed)
    size_t ai_in_cu_buf_size_ = 0;

    std::mutex ready_mutex_;
    std::mutex push_mutex_;
    std::mutex trace_mutex_;
    // Serializes EVERY thread's touch of the shared ID3D11Device/context (decode's copy,
    // push_ai_frame's CUDA-interop + copy, present's whole draw_and_present call, seek's
    // copy) -- see the file header for why this exists on top of SetMultithreadProtected(TRUE).
    std::mutex d3d_mutex_;
    // Serializes the Decoder object itself AND the ring-write+tag that immediately follows
    // each decode, between decode_loop() and seek() -- see the file header for the race this
    // closes (widened from spike2's narrower "just guard the Decoder object" scope).
    std::mutex decoder_mutex_;

    Decoder decoder_;
    double fps_ = 60.0;
    int64_t frame_count_ = 0;

    std::thread decode_thread_;
    std::thread present_thread_;
    std::atomic<bool> stop_{ false };

    LARGE_INTEGER pace_origin_qpc_{};
    LARGE_INTEGER freq_{};
    std::atomic<int64_t> present_head_frame_{ 0 };

    // Transport/seek state (see play()/pause()/seek()/present_loop()).
    std::atomic<bool> playing_{ false };
    std::atomic<int64_t> anchor_frame_{ 0 };   // content frame_num at anchor_qpc_ticks_
    std::atomic<int64_t> anchor_qpc_ticks_{ 0 }; // QPC ticks corresponding to anchor_frame_
    std::atomic<int64_t> clock_frame_{ 0 };    // last frame_num computed/shown by present_loop
    std::atomic<uint64_t> seek_version_{ 0 };
    std::atomic<int64_t> seek_slot_hint_{ 0 };

    std::vector<int64_t> present_qpc_ns_;   // guarded by trace_mutex_
    std::vector<int8_t> present_source_;    // guarded by trace_mutex_
    std::vector<int64_t> present_frame_num_; // guarded by trace_mutex_

    std::atomic<uint64_t> present_count_{ 0 };
    std::atomic<uint64_t> decode_frame_count_{ 0 };
    std::atomic<uint64_t> ai_push_count_{ 0 };
    std::atomic<uint64_t> n_ai_fresh_{ 0 }, n_ai_stale_{ 0 }, n_pt_fresh_{ 0 }, n_pt_stale_{ 0 };
};

namespace {

// WndProc's full DEFINITION (declared above, before class Player -- see that declaration's
// header comment for why it had to move here: it needs a complete Player type). This reopened
// block is the SAME unnamed namespace as the one earlier in this translation unit, so g_quit
// remains visible here unqualified.
//
// ImGui_ImplWin32_WndProcHandler is given first crack at every message (confirmed by reading
// backends/imgui_impl_win32.cpp: for every keyboard/mouse message it always returns 0/never
// consumes, except a couple of WM_IME_* paths that return 1 -- so this "return true" idiom is
// standard boilerplate here, not an observed short-circuit of our own switch below).
LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    Player* self = reinterpret_cast<Player*>(GetWindowLongPtrA(hwnd, GWLP_USERDATA));
    if (self && self->ui_ready()) {
        if (ImGui_ImplWin32_WndProcHandler(hwnd, msg, wp, lp))
            return true;
    }

    switch (msg) {
    case WM_DESTROY:
        g_quit = true;
        PostQuitMessage(0);
        return 0;
    case WM_CLOSE:
        DestroyWindow(hwnd);
        return 0;
    case WM_KEYDOWN:
        if (wp == VK_ESCAPE) {
            // ESC always quits, regardless of ImGui's keyboard-capture state (unchanged M1/M2
            // behavior) -- an escape hatch that must never be swallowed by a focused widget.
            g_quit = true;
            PostQuitMessage(0);
            return 0;
        }
        if (self && self->ui_ready() && !ImGui::GetIO().WantCaptureKeyboard) {
            if (wp == VK_SPACE) {
                self->record_toggle_play();
            } else if (wp == VK_LEFT || wp == VK_RIGHT) {
                int64_t fc = self->frame_count();
                int64_t step = static_cast<int64_t>(std::llround(5.0 * self->fps()));
                int64_t target = self->current_frame() + (wp == VK_LEFT ? -step : step);
                target = (fc > 0) ? std::clamp<int64_t>(target, 0, fc - 1) : std::max<int64_t>(0, target);
                self->record_seek(target);
            }
        }
        return 0;
    case WM_SYSKEYDOWN:
        if (wp == VK_RETURN) return 0; // swallow Alt+Enter, no exclusive fullscreen here
        break;
    default:
        break;
    }
    return DefWindowProc(hwnd, msg, wp, lp);
}

} // namespace

PYBIND11_MODULE(sumu_core, m)
{
    m.doc() = "sumu native present kernel: clock-driven decode/present/AI-mix with seek=reposition";

    py::class_<Player>(m, "Player")
        .def(py::init<int, int, bool>(),
            py::arg("width_hint") = 1280, py::arg("height_hint") = 720, py::arg("maximized") = false)
        .def("open", &Player::open, py::arg("path"))
        .def("play", &Player::play)
        .def("pause", &Player::pause)
        .def("is_playing", &Player::is_playing)
        .def("ui_tick", &Player::ui_tick) // M2: main-thread NewFrame/build/Render/publish tick
        .def("ui_ready", &Player::ui_ready)
        .def("path", &Player::path)
        .def("set_ui_config", &Player::set_ui_config, py::arg("clip_length"), py::arg("max_regions"))
        .def("take_ui_intents", &Player::take_ui_intents) // M3: drains + clears ui_intents_
        .def("seek", &Player::seek, py::arg("frame_num"))
        .def("push_ai_frame", &Player::push_ai_frame,
            py::arg("frame_num"), py::arg("dev_ptr"), py::arg("width"), py::arg("height"), py::arg("pitch_bytes"))
        .def("get_cuda_nv12_by_frame", &Player::get_cuda_nv12_by_frame, py::arg("frame_num"))
        .def("current_frame", &Player::current_frame)
        .def("frame_count", &Player::frame_count)
        .def("fps", &Player::fps)
        .def("dims", &Player::dims)
        .def("ai_hit_rate", &Player::ai_hit_rate)
        .def("present_stats", &Player::present_stats)
        .def("stats", &Player::stats)
        .def("dump_present_trace", &Player::dump_present_trace, py::arg("path"))
        .def("pump_messages", &Player::pump_messages)
        .def("should_quit", &Player::should_quit)
        .def("close", &Player::close);
}
