// SPDX-FileCopyrightText: sumu Authors
// SPDX-License-Identifier: AGPL-3.0
//
// sumu's promoted native present kernel (pybind11 module `sumu_core`, class `Player`).
// Promoted from the three validated spikes (see docs/spike_results.md):
//   - spike0_d3d11_present: D3D11 flip-model swapchain + FFmpeg d3d11va zero-copy decode.
//   - spike1_cuda_interop:  CUDA driver-API + torch primary context, zero-copy CUDA<->D3D11.
//   - spike2_clock_mixing:  three-thread clock-driven mixing kernel (decode thread + original
//                           ring buffer, AI-push thread + ready-map, present thread wall-clock
//                           frame picking, single explicit d3d_mutex_ serializing ALL threads'
//                           touches of the shared D3D11/CUDA-interop context -- this was
//                           spike2's key architectural finding and is preserved verbatim).
//
// New in this promotion: seek(frame_num) as a REPOSITION, not a teardown (I6) -- see the
// seek() method below and docs/native_core.md for the full design writeup and measurements.
//
// Threading model (unchanged from spike2, see spike2's presenter.cpp header for the full
// story of why a single d3d_mutex_ is required on top of ID3D11Multithread::SetMultithread-
// Protected(TRUE)):
//   - decode thread:  FFmpeg d3d11va decode -> CopySubresourceRegion into a persistent NV12
//                     "passthrough ring" Texture2DArray, throttled to stay within
//                     kDecodeAheadMax frames of the present head.
//   - AI-push thread (Python, not owned here): push_ai_frame() does the CUDA<->D3D11
//                     zero-copy bridge into a landing texture, then a CopySubresourceRegion
//                     into the AI ready-map's Texture2DArray slot, THEN marks that slot ready.
//   - present thread: wall-clock QPC pacing, picks AI-fresh -> passthrough-fresh -> repeat-
//                     last-shown every tick, NEVER blocks on decode or AI-push.
//
// seek()'s concurrency contract (the new part): `decoder_mutex_` now wraps not just the
// Decoder object itself but the WHOLE "produce one frame, copy it into the ring, tag it
// ready" sequence in BOTH decode_loop() and seek() -- widened from spike2's narrower "just
// guard the Decoder object" scope. This makes "decode one frame and publish it" an atomic
// unit with respect to seek(), which is what closes a real race: without this widening, a
// frame the decode thread had already pulled from the OLD position (in flight between
// Decoder::next_frame() returning and its ring-write+tag landing) could still land in the
// ring AFTER seek()'s own fresh write to the same slot, silently overwriting the just-sought
// frame with stale content while its tag looked fine. See docs/native_core.md for the full
// writeup and the seek-stress measurements that exercised this path.

#ifndef NOMINMAX
#define NOMINMAX // windows.h's min/max macros otherwise break std::min/std::max call sites below
#endif
#include <windows.h>
#include <d3d11.h>
#include <d3d11_4.h>
#include <dxgi1_2.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <timeapi.h>
#pragma comment(lib, "winmm.lib")

#include <cuda.h>
#include <cudaD3D11.h>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <atomic>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

#include "decoder.h"
#include "present_hlsl.h" // generated by native/cmake/embed_shader.cmake from native/shaders/present.hlsl

namespace py = pybind11;
using Microsoft::WRL::ComPtr;

namespace {

// ---- error helpers -----------------------------------------------------------------------

void check_hr(HRESULT hr, const char* what)
{
    if (FAILED(hr)) {
        char buf[256];
        snprintf(buf, sizeof(buf), "%s failed: hr=0x%08lx", what, hr);
        throw std::runtime_error(buf);
    }
}

void check_cu(CUresult res, const char* what)
{
    if (res != CUDA_SUCCESS) {
        const char* name = nullptr;
        const char* desc = nullptr;
        cuGetErrorName(res, &name);
        cuGetErrorString(res, &desc);
        char buf[512];
        snprintf(buf, sizeof(buf), "%s failed: CUresult=%d (%s: %s)", what,
            static_cast<int>(res), name ? name : "?", desc ? desc : "?");
        throw std::runtime_error(buf);
    }
}

// ---- global Win32 state (one window per process, fine for this player) --------------------
bool g_quit = false;

LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
    case WM_DESTROY:
        g_quit = true;
        PostQuitMessage(0);
        return 0;
    case WM_CLOSE:
        DestroyWindow(hwnd);
        return 0;
    case WM_KEYDOWN:
        if (wp == VK_ESCAPE) {
            g_quit = true;
            PostQuitMessage(0);
        }
        return 0;
    case WM_SYSKEYDOWN:
        if (wp == VK_RETURN) return 0; // swallow Alt+Enter, no exclusive fullscreen here
        break;
    default:
        break;
    }
    return DefWindowProc(hwnd, msg, wp, lp);
}

double pctile(std::vector<double>& sorted_ms, double q)
{
    if (sorted_ms.empty()) return 0.0;
    double pos = q * (sorted_ms.size() - 1);
    size_t lo = static_cast<size_t>(pos);
    size_t hi = std::min(lo + 1, sorted_ms.size() - 1);
    double frac = pos - lo;
    return sorted_ms[lo] * (1.0 - frac) + sorted_ms[hi] * frac;
}

py::dict summarize(std::vector<double> samples_ms)
{
    py::dict d;
    if (samples_ms.empty()) {
        d["n"] = 0; d["median_ms"] = 0.0; d["p99_ms"] = 0.0; d["max_ms"] = 0.0; d["mean_ms"] = 0.0;
        return d;
    }
    std::sort(samples_ms.begin(), samples_ms.end());
    double sum = 0.0;
    for (double v : samples_ms) sum += v;
    d["n"] = samples_ms.size();
    d["median_ms"] = pctile(samples_ms, 0.5);
    d["p99_ms"] = pctile(samples_ms, 0.99);
    d["max_ms"] = samples_ms.back();
    d["min_ms"] = samples_ms.front();
    d["mean_ms"] = sum / samples_ms.size();
    return d;
}

// Present-tick "source" tags recorded in the trace, distinguishing a freshly-drawn frame
// from a repeat-of-last-frame fallback (the latter should be ~never once steady, except
// briefly right after a seek while decode catches up to the new position).
enum class Source : int8_t {
    PassthroughFresh = 0,
    AiFresh = 1,
    PassthroughStale = 2, // re-presented because neither map had this exact frame_num
    AiStale = 3,
};

bool is_ai(Source s) { return s == Source::AiFresh || s == Source::AiStale; }

} // namespace

// ---------------------------------------------------------------------------------------
class Player
{
public:
    // Ring capacity in frames (~1s at 60fps): both the passthrough decode-ahead buffer and
    // the AI ready-map share this capacity/indexing scheme (see docs/spike_results.md's
    // spike2 writeup for the E_OUTOFMEMORY history behind this number).
    static constexpr UINT kRingCapacity = 64;
    static constexpr int64_t kDecodeAheadMax = static_cast<int64_t>(kRingCapacity) - 10;
    static constexpr int64_t kStartBufferFrames = 5;

    Player(int width_hint, int height_hint, bool maximized)
    {
        timeBeginPeriod(1);
        timer_period_set_ = true;

        create_window(width_hint, height_hint, maximized);
        create_device_and_swapchain();
        create_shader_pipeline();
        init_cuda_driver(); // device-independent-of-video-size CUDA setup only; landing
                             // texture + registration happen in open() once src dims are known.
    }

    ~Player() { close(); }

    // ---- lifecycle -------------------------------------------------------------------------

    void open(const std::string& video_path)
    {
        if (opened_) throw std::runtime_error("Player.open() called twice on the same Player");

        std::string decode_err;
        if (!decoder_.open(video_path, device_.Get(), decode_err))
            throw std::runtime_error("decoder.open failed: " + decode_err);
        fps_ = decoder_.fps();
        src_width_ = decoder_.width();
        src_height_ = decoder_.height();
        frame_count_ = decoder_.frame_count();
        if (src_width_ <= 0 || src_height_ <= 0)
            throw std::runtime_error("decoder reported invalid dimensions");

        create_ring_resources();
        create_landing_texture();
        register_landing_with_cuda();

        pt_tag_.assign(kRingCapacity, -1);
        ai_tag_.assign(kRingCapacity, -1);

        QueryPerformanceFrequency(&freq_);

        // Decode thread starts immediately and races ahead (throttled) of the present head,
        // which is still -1 (not started) at this point -- the throttle treats a not-yet-
        // started present head as "0" so decode can still build the initial buffer.
        stop_.store(false, std::memory_order_relaxed);
        decode_thread_ = std::thread(&Player::decode_loop, this);

        LARGE_INTEGER t0;
        QueryPerformanceCounter(&t0);
        for (;;) {
            if (pt_high_water_.load(std::memory_order_relaxed) >= kStartBufferFrames - 1)
                break;
            LARGE_INTEGER now;
            QueryPerformanceCounter(&now);
            double waited_s = static_cast<double>(now.QuadPart - t0.QuadPart) / qpc_freq_d();
            if (waited_s > 10.0)
                throw std::runtime_error("decode thread failed to buffer initial frames within 10s");
            Sleep(1);
        }

        // Start paused at frame 0 -- caller must call play() to start the wall clock.
        anchor_frame_.store(0, std::memory_order_relaxed);
        clock_frame_.store(0, std::memory_order_relaxed);
        present_head_frame_.store(0, std::memory_order_relaxed);
        playing_.store(false, std::memory_order_relaxed);
        QueryPerformanceCounter(&pace_origin_qpc_);
        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        anchor_qpc_ticks_.store(now.QuadPart, std::memory_order_relaxed);

        opened_ = true;
        present_thread_ = std::thread(&Player::present_loop, this);
    }

    void close()
    {
        if (closed_) return;
        closed_ = true;
        stop_.store(true, std::memory_order_relaxed);
        if (decode_thread_.joinable()) decode_thread_.join();
        if (present_thread_.joinable()) present_thread_.join();

        if (cu_res_) { cuGraphicsUnregisterResource(cu_res_); cu_res_ = nullptr; }
        if (cu_ctx_) { cuCtxSetCurrent(nullptr); cuDevicePrimaryCtxRelease(cu_dev_); cu_ctx_ = nullptr; }

        decoder_.close();

        if (hwnd_) { DestroyWindow(hwnd_); hwnd_ = nullptr; }
        if (timer_period_set_) { timeEndPeriod(1); timer_period_set_ = false; }
    }

    void pump_messages()
    {
        MSG msg{};
        while (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE)) {
            if (msg.message == WM_QUIT) { g_quit = true; break; }
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }

    bool should_quit() const { return g_quit; }

    // ---- transport control -------------------------------------------------------------

    void play()
    {
        require_open();
        if (playing_.load(std::memory_order_relaxed)) return;
        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        anchor_qpc_ticks_.store(now.QuadPart, std::memory_order_relaxed);
        anchor_frame_.store(clock_frame_.load(std::memory_order_relaxed), std::memory_order_relaxed);
        playing_.store(true, std::memory_order_relaxed);
    }

    void pause()
    {
        require_open();
        if (!playing_.load(std::memory_order_relaxed)) return;
        anchor_frame_.store(clock_frame_.load(std::memory_order_relaxed), std::memory_order_relaxed);
        playing_.store(false, std::memory_order_relaxed);
    }

    bool is_playing() const { return playing_.load(std::memory_order_relaxed); }

    // I6: seek = reposition, never teardown. Never touches decode_thread_/present_thread_/
    // decoder_/swapchain_ lifetime. Synchronous cost is dominated by Decoder::seek_to_frame's
    // own av_seek_frame + forward-decode-to-target (measured in docs/native_core.md); this
    // function does a bounded, small amount of extra D3D11/bookkeeping work on top of that
    // and returns -- it does NOT wait for steady playback to resume (that happens
    // organically on the decode/present threads, per I2/I9, never blocking).
    //
    // Returns the ACTUAL landed frame number (I5: anchored to the real decoded PTS, which
    // may differ slightly from the requested frame_num near GOP boundaries or EOF).
    int64_t seek(int64_t frame_num)
    {
        require_open();
        if (frame_count_ > 0) {
            frame_num = std::max<int64_t>(0, std::min<int64_t>(frame_num, frame_count_ - 1));
        } else {
            frame_num = std::max<int64_t>(0, frame_num);
        }

        // Widened lock: makes "seek the decoder, copy the landed frame into the ring, tag
        // it ready" one atomic unit with respect to decode_loop()'s own "decode one frame,
        // copy it, tag it" unit -- see the file header for the race this closes.
        std::lock_guard<std::mutex> decoder_lock(decoder_mutex_);

        DecodedFrame df;
        std::string err;
        if (!decoder_.seek_to_frame(frame_num, df, err))
            throw std::runtime_error("seek_to_frame failed: " + err);

        int64_t actual_frame = static_cast<int64_t>(std::llround(df.pts_seconds * fps_));
        UINT slot = wrap_slot(actual_frame);

        {
            std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
            context_->CopySubresourceRegion(pt_ring_tex_.Get(), slot, 0, 0, 0,
                df.texture, df.array_slice, nullptr);
        }
        {
            // Clear the WHOLE ready-map (both rings): a seek invalidates essentially all of
            // a ~1s-deep buffer relative to the new position anyway (I6's "reset" step), and
            // clearing unconditionally is simplest-and-safe (present's fallback path never
            // blocks even if a slot briefly shows stale content, so being conservative here
            // costs nothing but a few repeated-frame present ticks while decode refills).
            std::lock_guard<std::mutex> lk(ready_mutex_);
            std::fill(pt_tag_.begin(), pt_tag_.end(), -1);
            std::fill(ai_tag_.begin(), ai_tag_.end(), -1);
            pt_tag_[slot] = actual_frame;
        }

        pt_high_water_.store(actual_frame, std::memory_order_relaxed);
        present_head_frame_.store(actual_frame, std::memory_order_relaxed);

        // Reposition the present clock anchor. If playing, present continues from here at
        // full speed; if paused, the frozen frame moves to actual_frame.
        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        anchor_qpc_ticks_.store(now.QuadPart, std::memory_order_relaxed);
        anchor_frame_.store(actual_frame, std::memory_order_relaxed);
        clock_frame_.store(actual_frame, std::memory_order_relaxed);

        // Tell the freshly-seeked slot/source to present_loop's stale-repeat fallback too,
        // so a post-seek tick that (due to scheduling) lands past actual_frame before decode
        // catches up repeats the CORRECT just-sought frame, not whatever was on screen pre-
        // seek. Guarded by ready_mutex_ alongside the tag arrays it's read next to.
        {
            std::lock_guard<std::mutex> lk(ready_mutex_);
            seek_slot_hint_.store(static_cast<int64_t>(slot), std::memory_order_relaxed);
        }
        seek_version_.fetch_add(1, std::memory_order_relaxed);

        return actual_frame;
    }

    // ---- AI insertion point --------------------------------------------------------------

    // dev_ptr: CUdeviceptr (torch tensor's data_ptr()) for a contiguous uint8 RGBA8 (H,W,4)
    // tensor representing the AI-processed frame for content frame number `frame_num`. Never
    // blocks the present thread -- only ever touches the small landing texture via CUDA,
    // then a single D3D11 copy into the ready-map slot, then flips that slot's tag.
    void push_ai_frame(int64_t frame_num, uint64_t dev_ptr, int fwidth, int fheight, size_t pitch_bytes)
    {
        require_open();
        if (fwidth != src_width_ || fheight != src_height_)
            throw std::runtime_error("push_ai_frame: frame size does not match source video size");

        std::lock_guard<std::mutex> push_lock(push_mutex_); // defensive: single-producer assumed

        // push_ai_frame is called from whatever OS thread Python's AI-producer thread is --
        // driver-API calls issued directly here do not get CUDA runtime's lazy implicit
        // context attach, so make it explicit and unconditional.
        check_cu(cuCtxSetCurrent(cu_ctx_), "cuCtxSetCurrent (push_ai_frame)");

        std::lock_guard<std::mutex> d3d_lock(d3d_mutex_); // serializes ALL D3D11/CUDA-interop use of the shared context

        try {
            check_cu(cuGraphicsMapResources(1, &cu_res_, 0), "cuGraphicsMapResources");
            CUarray cu_arr = nullptr;
            check_cu(cuGraphicsSubResourceGetMappedArray(&cu_arr, cu_res_, 0, 0),
                "cuGraphicsSubResourceGetMappedArray");

            CUDA_MEMCPY2D cp{};
            cp.srcMemoryType = CU_MEMORYTYPE_DEVICE;
            cp.srcDevice = static_cast<CUdeviceptr>(dev_ptr);
            cp.srcPitch = pitch_bytes;
            cp.dstMemoryType = CU_MEMORYTYPE_ARRAY;
            cp.dstArray = cu_arr;
            cp.WidthInBytes = static_cast<size_t>(fwidth) * 4;
            cp.Height = static_cast<size_t>(fheight);
            check_cu(cuMemcpy2D(&cp), "cuMemcpy2D (device -> mapped landing array)");

            check_cu(cuGraphicsUnmapResources(1, &cu_res_, 0), "cuGraphicsUnmapResources");

            UINT slot = wrap_slot(frame_num);
            context_->CopySubresourceRegion(ai_ring_tex_.Get(), slot, 0, 0, 0,
                landing_tex_.Get(), 0, nullptr);

            {
                std::lock_guard<std::mutex> lk(ready_mutex_);
                ai_tag_[slot] = frame_num; // only mark ready AFTER the copy above is issued
            }
            ++ai_push_count_;
        } catch (const std::exception& e) {
            HRESULT removed = device_ ? device_->GetDeviceRemovedReason() : S_OK;
            char buf[768];
            snprintf(buf, sizeof(buf), "%s [device_removed_reason=0x%08lx]", e.what(),
                static_cast<unsigned long>(removed));
            throw std::runtime_error(buf);
        }
    }

    // ---- introspection -------------------------------------------------------------------

    double fps() const { return fps_; }
    int64_t frame_count() const { return frame_count_; }
    int64_t current_frame() const { return clock_frame_.load(std::memory_order_relaxed); }
    std::pair<int, int> dims() const { return { src_width_, src_height_ }; }

    double ai_hit_rate() const
    {
        uint64_t pc = present_count_.load(std::memory_order_relaxed);
        if (pc == 0) return 0.0;
        return static_cast<double>(n_ai_fresh_.load(std::memory_order_relaxed)) / static_cast<double>(pc);
    }

    py::dict stats()
    {
        py::dict d;
        d["fps"] = fps_;
        d["frame_count"] = frame_count_;
        d["present_count"] = present_count_.load(std::memory_order_relaxed);
        d["decode_frame_count"] = decode_frame_count_.load(std::memory_order_relaxed);
        d["ai_push_count"] = ai_push_count_.load(std::memory_order_relaxed);
        d["n_ai_fresh"] = n_ai_fresh_.load(std::memory_order_relaxed);
        d["n_ai_stale"] = n_ai_stale_.load(std::memory_order_relaxed);
        d["n_pt_fresh"] = n_pt_fresh_.load(std::memory_order_relaxed);
        d["n_pt_stale"] = n_pt_stale_.load(std::memory_order_relaxed);
        d["ai_hit_rate"] = ai_hit_rate();
        d["is_playing"] = playing_.load(std::memory_order_relaxed);
        d["current_frame"] = current_frame();
        return d;
    }

    // Present-interval (ms) median/p99/etc, computed on demand from the in-memory trace so
    // far -- safe to call while playing (trace_mutex_ guards the vectors present_loop()
    // appends to every tick).
    py::dict present_stats()
    {
        std::vector<double> intervals_ms;
        {
            std::lock_guard<std::mutex> lk(trace_mutex_);
            intervals_ms.reserve(present_qpc_ns_.size());
            for (size_t i = 1; i < present_qpc_ns_.size(); ++i)
                intervals_ms.push_back(static_cast<double>(present_qpc_ns_[i] - present_qpc_ns_[i - 1]) / 1e6);
        }
        return summarize(std::move(intervals_ms));
    }

    // trace CSV: qpc_ns,source,frame_num -- analyze_present.py (--format ns) only reads
    // column 0, so this stays compatible with the shared analysis tool while also carrying
    // the per-tick source tag for switch-point / seek-recovery analysis.
    void dump_present_trace(const std::string& path)
    {
        std::lock_guard<std::mutex> lk(trace_mutex_);
        std::ofstream f(path, std::ios::trunc);
        f << "qpc_ns,source,frame_num\n";
        for (size_t i = 0; i < present_qpc_ns_.size(); ++i) {
            f << present_qpc_ns_[i] << "," << static_cast<int>(present_source_[i]) << ","
              << present_frame_num_[i] << "\n";
        }
    }

private:
    void require_open() const
    {
        if (!opened_) throw std::runtime_error("Player.open() has not been called yet");
    }

    // ---- setup -----------------------------------------------------------------------------

    void create_window(int width_hint, int height_hint, bool maximized)
    {
        HINSTANCE hinst = GetModuleHandle(nullptr);
        WNDCLASSEXA wc{};
        wc.cbSize = sizeof(wc);
        wc.style = CS_HREDRAW | CS_VREDRAW;
        wc.lpfnWndProc = WndProc;
        wc.hInstance = hinst;
        wc.hCursor = LoadCursor(nullptr, IDC_ARROW);
        wc.lpszClassName = "Sumu_Player_WndClass";
        RegisterClassExA(&wc);

        RECT rc{ 0, 0, std::max(1, width_hint), std::max(1, height_hint) };
        AdjustWindowRect(&rc, WS_OVERLAPPEDWINDOW, FALSE);
        hwnd_ = CreateWindowExA(0, wc.lpszClassName, "sumu",
            WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT,
            rc.right - rc.left, rc.bottom - rc.top, nullptr, nullptr, hinst, nullptr);
        if (!hwnd_) throw std::runtime_error("CreateWindowEx failed");
        ShowWindow(hwnd_, maximized ? SW_SHOWMAXIMIZED : SW_SHOW);
        UpdateWindow(hwnd_);

        RECT client_rc;
        GetClientRect(hwnd_, &client_rc);
        win_width_ = static_cast<UINT>(std::max<LONG>(1, client_rc.right - client_rc.left));
        win_height_ = static_cast<UINT>(std::max<LONG>(1, client_rc.bottom - client_rc.top));
    }

    void create_device_and_swapchain()
    {
        D3D_FEATURE_LEVEL levels[] = { D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0 };
        D3D_FEATURE_LEVEL got{};
        HRESULT hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
            levels, ARRAYSIZE(levels), D3D11_SDK_VERSION, &device_, &got, &context_);
        check_hr(hr, "D3D11CreateDevice");

        // Present thread, decode thread, and the AI push thread (called from Python) all
        // issue calls on this same immediate context concurrently. Kept as defense-in-depth
        // alongside the explicit d3d_mutex_ (see file header) -- not a substitute for it.
        {
            ComPtr<ID3D11Multithread> mt;
            check_hr(device_.As(&mt), "QueryInterface(ID3D11Multithread)");
            mt->SetMultithreadProtected(TRUE);
        }

        ComPtr<IDXGIDevice> dxgi_device;
        device_.As(&dxgi_device);
        dxgi_device->GetAdapter(&adapter_);
        ComPtr<IDXGIFactory2> factory;
        adapter_->GetParent(IID_PPV_ARGS(&factory));

        DXGI_SWAP_CHAIN_DESC1 scd{};
        scd.Width = win_width_;
        scd.Height = win_height_;
        scd.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        scd.SampleDesc.Count = 1;
        scd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
        scd.BufferCount = 2;
        scd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
        scd.AlphaMode = DXGI_ALPHA_MODE_IGNORE;
        scd.Scaling = DXGI_SCALING_STRETCH;

        hr = factory->CreateSwapChainForHwnd(device_.Get(), hwnd_, &scd, nullptr, nullptr, &swapchain_);
        check_hr(hr, "CreateSwapChainForHwnd");
        factory->MakeWindowAssociation(hwnd_, DXGI_MWA_NO_ALT_ENTER);

        ComPtr<ID3D11Texture2D> backbuffer;
        swapchain_->GetBuffer(0, IID_PPV_ARGS(&backbuffer));
        hr = device_->CreateRenderTargetView(backbuffer.Get(), nullptr, &backbuffer_rtv_);
        check_hr(hr, "CreateRenderTargetView");
    }

    void create_shader_pipeline()
    {
        ComPtr<ID3DBlob> vs_blob, ps_nv12_blob, ps_ai_blob, err_blob;
        HRESULT hr = D3DCompile(kShaderSrc, strlen(kShaderSrc), "present.hlsl", nullptr, nullptr,
            "VSMain", "vs_5_0", 0, 0, &vs_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("VS compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        hr = D3DCompile(kShaderSrc, strlen(kShaderSrc), "present.hlsl", nullptr, nullptr,
            "PSMain_NV12", "ps_5_0", 0, 0, &ps_nv12_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("PS(NV12) compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        hr = D3DCompile(kShaderSrc, strlen(kShaderSrc), "present.hlsl", nullptr, nullptr,
            "PSMain_AI", "ps_5_0", 0, 0, &ps_ai_blob, &err_blob);
        if (FAILED(hr)) throw std::runtime_error("PS(AI) compile failed: " +
            std::string(err_blob ? (const char*)err_blob->GetBufferPointer() : "?"));

        check_hr(device_->CreateVertexShader(vs_blob->GetBufferPointer(), vs_blob->GetBufferSize(), nullptr, &vs_),
            "CreateVertexShader");
        check_hr(device_->CreatePixelShader(ps_nv12_blob->GetBufferPointer(), ps_nv12_blob->GetBufferSize(), nullptr, &ps_nv12_),
            "CreatePixelShader(NV12)");
        check_hr(device_->CreatePixelShader(ps_ai_blob->GetBufferPointer(), ps_ai_blob->GetBufferSize(), nullptr, &ps_ai_),
            "CreatePixelShader(AI)");

        D3D11_SAMPLER_DESC sd{};
        sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sd.ComparisonFunc = D3D11_COMPARISON_NEVER;
        sd.MaxLOD = D3D11_FLOAT32_MAX;
        check_hr(device_->CreateSamplerState(&sd, &sampler_), "CreateSamplerState");

        struct SliceCB { UINT arraySlice; UINT pad[3]; };
        D3D11_BUFFER_DESC cbd{};
        cbd.ByteWidth = sizeof(SliceCB);
        cbd.Usage = D3D11_USAGE_DYNAMIC;
        cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        check_hr(device_->CreateBuffer(&cbd, nullptr, &slice_cb_), "CreateBuffer(slice_cb_)");
    }

    void create_ring_resources()
    {
        D3D11_TEXTURE2D_DESC pt_desc{};
        pt_desc.Width = src_width_;
        pt_desc.Height = src_height_;
        pt_desc.MipLevels = 1;
        pt_desc.ArraySize = kRingCapacity;
        pt_desc.Format = DXGI_FORMAT_NV12;
        pt_desc.SampleDesc.Count = 1;
        pt_desc.Usage = D3D11_USAGE_DEFAULT;
        // NV12 is a video format; on this driver CreateTexture2D rejects it (E_INVALIDARG)
        // with BIND_SHADER_RESOURCE alone -- matching the decoder's own hw_frames_ctx bind
        // flags (BIND_DECODER | BIND_SHADER_RESOURCE) makes it succeed. We never actually
        // use this as a decode target, just as a same-format GPU-side copy destination + SRV
        // source.
        pt_desc.BindFlags = D3D11_BIND_DECODER | D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&pt_desc, nullptr, &pt_ring_tex_), "CreateTexture2D(pt_ring_tex_)");

        pt_srv_y_.resize(kRingCapacity);
        pt_srv_uv_.resize(kRingCapacity);
        for (UINT i = 0; i < kRingCapacity; ++i) {
            D3D11_SHADER_RESOURCE_VIEW_DESC yd{};
            yd.Format = DXGI_FORMAT_R8_UNORM;
            yd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2DARRAY;
            yd.Texture2DArray.MostDetailedMip = 0;
            yd.Texture2DArray.MipLevels = 1;
            yd.Texture2DArray.FirstArraySlice = i;
            yd.Texture2DArray.ArraySize = 1;
            check_hr(device_->CreateShaderResourceView(pt_ring_tex_.Get(), &yd, &pt_srv_y_[i]), "CreateSRV(pt Y)");

            D3D11_SHADER_RESOURCE_VIEW_DESC uvd = yd;
            uvd.Format = DXGI_FORMAT_R8G8_UNORM;
            check_hr(device_->CreateShaderResourceView(pt_ring_tex_.Get(), &uvd, &pt_srv_uv_[i]), "CreateSRV(pt UV)");
        }

        D3D11_TEXTURE2D_DESC ai_desc{};
        ai_desc.Width = src_width_;
        ai_desc.Height = src_height_;
        ai_desc.MipLevels = 1;
        ai_desc.ArraySize = kRingCapacity;
        ai_desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        ai_desc.SampleDesc.Count = 1;
        ai_desc.Usage = D3D11_USAGE_DEFAULT;
        ai_desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&ai_desc, nullptr, &ai_ring_tex_), "CreateTexture2D(ai_ring_tex_)");

        ai_srv_.resize(kRingCapacity);
        for (UINT i = 0; i < kRingCapacity; ++i) {
            D3D11_SHADER_RESOURCE_VIEW_DESC ad{};
            ad.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
            ad.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2DARRAY;
            ad.Texture2DArray.MostDetailedMip = 0;
            ad.Texture2DArray.MipLevels = 1;
            ad.Texture2DArray.FirstArraySlice = i;
            ad.Texture2DArray.ArraySize = 1;
            check_hr(device_->CreateShaderResourceView(ai_ring_tex_.Get(), &ad, &ai_srv_[i]), "CreateSRV(ai)");
        }
    }

    void create_landing_texture()
    {
        D3D11_TEXTURE2D_DESC td{};
        td.Width = src_width_;
        td.Height = src_height_;
        td.MipLevels = 1;
        td.ArraySize = 1;
        td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        td.SampleDesc.Count = 1;
        td.Usage = D3D11_USAGE_DEFAULT;
        td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        check_hr(device_->CreateTexture2D(&td, nullptr, &landing_tex_), "CreateTexture2D(landing_tex_)");
    }

    void init_cuda_driver()
    {
        check_cu(cuInit(0), "cuInit");
        check_cu(cuDeviceGet(&cu_dev_, 0), "cuDeviceGet");

        CUdevice dev_from_adapter = -1;
        CUresult r = cuD3D11GetDevice(&dev_from_adapter, adapter_.Get());
        if (r != CUDA_SUCCESS || dev_from_adapter != cu_dev_) {
            char buf[256];
            snprintf(buf, sizeof(buf),
                "cuD3D11GetDevice mismatch: D3D adapter maps to CUDA device %d, expected %d (CUresult=%d)",
                (int)dev_from_adapter, (int)cu_dev_, (int)r);
            throw std::runtime_error(buf);
        }

        check_cu(cuDevicePrimaryCtxRetain(&cu_ctx_, cu_dev_), "cuDevicePrimaryCtxRetain");
        check_cu(cuCtxSetCurrent(cu_ctx_), "cuCtxSetCurrent");
    }

    void register_landing_with_cuda()
    {
        check_cu(cuGraphicsD3D11RegisterResource(&cu_res_, landing_tex_.Get(), CU_GRAPHICS_REGISTER_FLAGS_NONE),
            "cuGraphicsD3D11RegisterResource");
    }

    // ---- decode thread -----------------------------------------------------------------------

    void decode_loop()
    {
        while (!stop_.load(std::memory_order_relaxed)) {
            // Throttle: never get more than kDecodeAheadMax frames ahead of the present
            // head, so we never overwrite a ring slot before present has had its one chance
            // to read it. Before the present thread has started, present_head_frame_ is
            // whatever open() initialized it to (0); after a seek it's the seeked frame.
            for (;;) {
                if (stop_.load(std::memory_order_relaxed)) return;
                int64_t head = present_head_frame_.load(std::memory_order_relaxed);
                int64_t high = pt_high_water_.load(std::memory_order_relaxed);
                if (high - head < kDecodeAheadMax) break;
                Sleep(1);
            }

            // Widened critical section (see file header): decode-one-frame + copy-into-ring
            // + tag-ready is one atomic unit with respect to seek()'s own reposition, so a
            // frame decoded from the OLD position can never land in the ring after a seek's
            // fresh write to the same slot.
            std::lock_guard<std::mutex> decoder_lock(decoder_mutex_);
            if (stop_.load(std::memory_order_relaxed)) return;

            DecodedFrame df;
            if (!decoder_.next_frame(df)) {
                // Unrecoverable decode error. Stop the whole run rather than spin; present
                // thread will keep re-presenting the last good frame forever via the
                // stale-fallback path rather than hitching.
                stop_.store(true, std::memory_order_relaxed);
                return;
            }

            int64_t frame_num = static_cast<int64_t>(std::llround(df.pts_seconds * fps_));
            UINT slot = wrap_slot(frame_num);

            {
                std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
                context_->CopySubresourceRegion(pt_ring_tex_.Get(), slot, 0, 0, 0,
                    df.texture, df.array_slice, nullptr);
            }
            {
                std::lock_guard<std::mutex> lk(ready_mutex_);
                pt_tag_[slot] = frame_num;
            }
            pt_high_water_.store(frame_num, std::memory_order_relaxed);
            ++decode_frame_count_;
        }
    }

    // ---- present thread ------------------------------------------------------------------------

    void present_loop()
    {
        const double ticks_per_ms = static_cast<double>(freq_.QuadPart) / 1000.0;
        int64_t last_frame_local = -1;
        Source last_actual_source = Source::PassthroughFresh;
        UINT last_actual_slot = 0;
        uint64_t local_seek_version = seek_version_.load(std::memory_order_relaxed);
        int64_t tick_idx = 0;

        {
            std::lock_guard<std::mutex> lk(trace_mutex_);
            present_qpc_ns_.reserve(1u << 16);
            present_source_.reserve(1u << 16);
            present_frame_num_.reserve(1u << 16);
        }

        while (!stop_.load(std::memory_order_relaxed)) {
            // Pacing engine: fixed cadence at fps_, independent of play/pause/seek state so
            // this thread never busy-spins and never needs tearing down/rebuilding across
            // transport changes.
            ++tick_idx;
            LARGE_INTEGER target_qpc;
            target_qpc.QuadPart = pace_origin_qpc_.QuadPart +
                static_cast<LONGLONG>(static_cast<double>(tick_idx) / fps_ * freq_.QuadPart);
            if (!wait_until_qpc_or_stop(target_qpc, ticks_per_ms)) break;

            uint64_t sv = seek_version_.load(std::memory_order_relaxed);
            bool just_seeked = (sv != local_seek_version);
            local_seek_version = sv;

            if (just_seeked) {
                // Bypass the monotonic guard below for exactly this tick (a seek can
                // legitimately move backward or far forward), and repoint the stale-repeat
                // fallback at the freshly-seeked slot so an immediately-following tick that
                // races ahead of decode never repeats pre-seek content.
                last_actual_slot = static_cast<UINT>(seek_slot_hint_.load(std::memory_order_relaxed));
                last_actual_source = Source::PassthroughFresh;
            }

            int64_t frame;
            if (playing_.load(std::memory_order_relaxed)) {
                LARGE_INTEGER now;
                QueryPerformanceCounter(&now);
                int64_t aq = anchor_qpc_ticks_.load(std::memory_order_relaxed);
                int64_t af = anchor_frame_.load(std::memory_order_relaxed);
                double elapsed_s = static_cast<double>(now.QuadPart - aq) / freq_.QuadPart;
                int64_t computed = af + static_cast<int64_t>(std::llround(elapsed_s * fps_));
                if (!just_seeked && computed <= last_frame_local) computed = last_frame_local + 1;
                frame = computed;
            } else {
                // Paused: frozen at anchor_frame_, present thread keeps redrawing it so the
                // heartbeat (present cadence) never stops even though content doesn't advance.
                frame = anchor_frame_.load(std::memory_order_relaxed);
            }
            last_frame_local = frame;
            clock_frame_.store(frame, std::memory_order_relaxed);
            present_head_frame_.store(frame, std::memory_order_relaxed);

            UINT slot = wrap_slot(frame);
            Source source;
            UINT use_slot;
            {
                std::lock_guard<std::mutex> lk(ready_mutex_);
                if (ai_tag_[slot] == frame) {
                    source = Source::AiFresh;
                    use_slot = slot;
                } else if (pt_tag_[slot] == frame) {
                    source = Source::PassthroughFresh;
                    use_slot = slot;
                } else {
                    // Neither map has this exact frame number ready. NEVER block -- just
                    // re-present whatever was actually shown last tick (I2/I9).
                    source = is_ai(last_actual_source) ? Source::AiStale : Source::PassthroughStale;
                    use_slot = last_actual_slot;
                }
            }

            {
                // Serializes ALL D3D11/CUDA-interop use of the shared context (see file
                // header). Decode/push threads are the ones who may occasionally wait a
                // fraction of a frame for this lock, never the reverse.
                std::lock_guard<std::mutex> d3d_lock(d3d_mutex_);
                draw_and_present(source, use_slot);
            }

            LARGE_INTEGER pres_now;
            QueryPerformanceCounter(&pres_now);
            {
                std::lock_guard<std::mutex> lk(trace_mutex_);
                present_qpc_ns_.push_back(qpc_to_ns(pres_now));
                present_source_.push_back(static_cast<int8_t>(source));
                present_frame_num_.push_back(frame);
            }
            present_count_.fetch_add(1, std::memory_order_relaxed);
            switch (source) {
            case Source::AiFresh: n_ai_fresh_.fetch_add(1, std::memory_order_relaxed); break;
            case Source::AiStale: n_ai_stale_.fetch_add(1, std::memory_order_relaxed); break;
            case Source::PassthroughFresh: n_pt_fresh_.fetch_add(1, std::memory_order_relaxed); break;
            case Source::PassthroughStale: n_pt_stale_.fetch_add(1, std::memory_order_relaxed); break;
            }

            if (source == Source::AiFresh || source == Source::PassthroughFresh) {
                last_actual_source = source;
                last_actual_slot = use_slot;
            }
        }
    }

    void draw_and_present(Source source, UINT slot)
    {
        D3D11_VIEWPORT vp{ 0.0f, 0.0f, static_cast<float>(win_width_), static_cast<float>(win_height_), 0.0f, 1.0f };
        context_->RSSetViewports(1, &vp);
        ID3D11RenderTargetView* rtvs[] = { backbuffer_rtv_.Get() };
        context_->OMSetRenderTargets(1, rtvs, nullptr);
        context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        context_->VSSetShader(vs_.Get(), nullptr, 0);

        struct SliceCB { UINT arraySlice; UINT pad[3]; };
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (SUCCEEDED(context_->Map(slice_cb_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
            SliceCB cb{ slot, {0, 0, 0} };
            memcpy(mapped.pData, &cb, sizeof(cb));
            context_->Unmap(slice_cb_.Get(), 0);
        }
        ID3D11Buffer* cbs[] = { slice_cb_.Get() };
        context_->PSSetConstantBuffers(0, 1, cbs);
        ID3D11SamplerState* samplers[] = { sampler_.Get() };
        context_->PSSetSamplers(0, 1, samplers);

        if (is_ai(source)) {
            context_->PSSetShader(ps_ai_.Get(), nullptr, 0);
            ID3D11ShaderResourceView* srvs[] = { ai_srv_[slot].Get() };
            context_->PSSetShaderResources(2, 1, srvs);
        } else {
            context_->PSSetShader(ps_nv12_.Get(), nullptr, 0);
            ID3D11ShaderResourceView* srvs[] = { pt_srv_y_[slot].Get(), pt_srv_uv_[slot].Get() };
            context_->PSSetShaderResources(0, 2, srvs);
        }

        context_->Draw(3, 0);
        swapchain_->Present(1, 0);
    }

    // ---- helpers -----------------------------------------------------------------------------

    static UINT wrap_slot(int64_t frame_num)
    {
        int64_t m = frame_num % static_cast<int64_t>(kRingCapacity);
        if (m < 0) m += kRingCapacity;
        return static_cast<UINT>(m);
    }

    static double qpc_freq_d()
    {
        LARGE_INTEGER f;
        QueryPerformanceFrequency(&f);
        return static_cast<double>(f.QuadPart);
    }

    static int64_t qpc_to_ns(LARGE_INTEGER c)
    {
        double ns_per_tick = 1e9 / qpc_freq_d();
        return static_cast<int64_t>(static_cast<double>(c.QuadPart) * ns_per_tick + 0.5);
    }

    // Hybrid sleep+spin wait (same strategy as spike 0/2), periodically checking stop_ so
    // close() doesn't have to wait out a full frame interval. Returns false if stop was
    // requested before the deadline.
    bool wait_until_qpc_or_stop(LARGE_INTEGER target, double ticks_per_ms)
    {
        LARGE_INTEGER now;
        for (;;) {
            if (stop_.load(std::memory_order_relaxed)) return false;
            QueryPerformanceCounter(&now);
            double remaining_ms = static_cast<double>(target.QuadPart - now.QuadPart) / ticks_per_ms;
            if (remaining_ms <= 0.0) return true;
            if (remaining_ms > 2.0) {
                Sleep(static_cast<DWORD>(std::min(remaining_ms - 1.0, 5.0)));
            } else {
                YieldProcessor();
            }
        }
    }

    // ---- state -------------------------------------------------------------------------------

    int src_width_ = 0;
    int src_height_ = 0;
    UINT win_width_ = 0;
    UINT win_height_ = 0;
    HWND hwnd_ = nullptr;
    bool timer_period_set_ = false;
    bool closed_ = false;
    bool opened_ = false;

    ComPtr<ID3D11Device> device_;
    ComPtr<ID3D11DeviceContext> context_;
    ComPtr<IDXGIAdapter> adapter_;
    ComPtr<IDXGISwapChain1> swapchain_;
    ComPtr<ID3D11RenderTargetView> backbuffer_rtv_;
    ComPtr<ID3D11VertexShader> vs_;
    ComPtr<ID3D11PixelShader> ps_nv12_;
    ComPtr<ID3D11PixelShader> ps_ai_;
    ComPtr<ID3D11SamplerState> sampler_;
    ComPtr<ID3D11Buffer> slice_cb_;

    ComPtr<ID3D11Texture2D> pt_ring_tex_;
    std::vector<ComPtr<ID3D11ShaderResourceView>> pt_srv_y_;
    std::vector<ComPtr<ID3D11ShaderResourceView>> pt_srv_uv_;
    std::vector<int64_t> pt_tag_; // guarded by ready_mutex_
    std::atomic<int64_t> pt_high_water_{ -1 };

    ComPtr<ID3D11Texture2D> ai_ring_tex_;
    std::vector<ComPtr<ID3D11ShaderResourceView>> ai_srv_;
    std::vector<int64_t> ai_tag_; // guarded by ready_mutex_

    ComPtr<ID3D11Texture2D> landing_tex_;
    CUdevice cu_dev_ = 0;
    CUcontext cu_ctx_ = nullptr;
    CUgraphicsResource cu_res_ = nullptr;

    std::mutex ready_mutex_;
    std::mutex push_mutex_;
    std::mutex trace_mutex_;
    // Serializes EVERY thread's touch of the shared ID3D11Device/context (decode's copy,
    // push_ai_frame's CUDA-interop + copy, present's whole draw_and_present call, seek's
    // copy) -- see the file header for why this exists on top of SetMultithreadProtected(TRUE).
    std::mutex d3d_mutex_;
    // Serializes the Decoder object itself AND the ring-write+tag that immediately follows
    // each decode, between decode_loop() and seek() -- see the file header for the race this
    // closes (widened from spike2's narrower "just guard the Decoder object" scope).
    std::mutex decoder_mutex_;

    Decoder decoder_;
    double fps_ = 60.0;
    int64_t frame_count_ = 0;

    std::thread decode_thread_;
    std::thread present_thread_;
    std::atomic<bool> stop_{ false };

    LARGE_INTEGER pace_origin_qpc_{};
    LARGE_INTEGER freq_{};
    std::atomic<int64_t> present_head_frame_{ 0 };

    // Transport/seek state (see play()/pause()/seek()/present_loop()).
    std::atomic<bool> playing_{ false };
    std::atomic<int64_t> anchor_frame_{ 0 };   // content frame_num at anchor_qpc_ticks_
    std::atomic<int64_t> anchor_qpc_ticks_{ 0 }; // QPC ticks corresponding to anchor_frame_
    std::atomic<int64_t> clock_frame_{ 0 };    // last frame_num computed/shown by present_loop
    std::atomic<uint64_t> seek_version_{ 0 };
    std::atomic<int64_t> seek_slot_hint_{ 0 };

    std::vector<int64_t> present_qpc_ns_;   // guarded by trace_mutex_
    std::vector<int8_t> present_source_;    // guarded by trace_mutex_
    std::vector<int64_t> present_frame_num_; // guarded by trace_mutex_

    std::atomic<uint64_t> present_count_{ 0 };
    std::atomic<uint64_t> decode_frame_count_{ 0 };
    std::atomic<uint64_t> ai_push_count_{ 0 };
    std::atomic<uint64_t> n_ai_fresh_{ 0 }, n_ai_stale_{ 0 }, n_pt_fresh_{ 0 }, n_pt_stale_{ 0 };
};

PYBIND11_MODULE(sumu_core, m)
{
    m.doc() = "sumu native present kernel: clock-driven decode/present/AI-mix with seek=reposition";

    py::class_<Player>(m, "Player")
        .def(py::init<int, int, bool>(),
            py::arg("width_hint") = 1280, py::arg("height_hint") = 720, py::arg("maximized") = false)
        .def("open", &Player::open, py::arg("path"))
        .def("play", &Player::play)
        .def("pause", &Player::pause)
        .def("is_playing", &Player::is_playing)
        .def("seek", &Player::seek, py::arg("frame_num"))
        .def("push_ai_frame", &Player::push_ai_frame,
            py::arg("frame_num"), py::arg("dev_ptr"), py::arg("width"), py::arg("height"), py::arg("pitch_bytes"))
        .def("current_frame", &Player::current_frame)
        .def("frame_count", &Player::frame_count)
        .def("fps", &Player::fps)
        .def("dims", &Player::dims)
        .def("ai_hit_rate", &Player::ai_hit_rate)
        .def("present_stats", &Player::present_stats)
        .def("stats", &Player::stats)
        .def("dump_present_trace", &Player::dump_present_trace, py::arg("path"))
        .def("pump_messages", &Player::pump_messages)
        .def("should_quit", &Player::should_quit)
        .def("close", &Player::close);
}
